### ISSUE TITLE
Failed to download coco dataset with scripts.

### ISSUE THREAD

**Issue by zhengsx** [zhanghang1989/PyTorch-Encoding#105]
Hi, when I run 
`python scripts/prepare_coco.py`
I met an error:

Downloading /home/shuzhe/.encoding/data/train2017.zip from http://images.cocodataset.org/zips/train2017.zip...
18883655KB [24:39, 12763.77KB/s]
Downloading /home/shuzhe/.encoding/data/annotations_trainval2017.zip from http://images.cocodataset.org/annotations/annotations_trainval2017.zip...
246981KB [00:36, 6711.31KB/s]
Downloading /home/shuzhe/.encoding/data/val2017.zip from http://images.cocodataset.org/zips/val2017.zip...
796471KB [01:18, 10107.25KB/s]
Downloading /home/shuzhe/.encoding/data/stuff_annotations_trainval2017.zip from http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip...
1121767KB [01:43, 10834.76KB/s]
Traceback (most recent call last):
  File "prepare_coco.py", line 60, in <module>
    download_coco(_TARGET_DIR, overwrite=False)
  File "prepare_coco.py", line 34, in download_coco
    filename = download(url, path=path, overwrite=overwrite, sha1_hash=checksum)
  File "/home/shuzhe/anaconda3/lib/python3.6/site-packages/encoding/utils/files.py", line 76, in download
    'the default repo.'.format(fname))
UserWarning: File /home/shuzhe/.encoding/data/stuff_annotations_trainval2017.zip is downloaded but the content hash does not match. The repo may be outdated or download may be incomplete. If the "repo_url" is overridden, consider switching to the default repo.

**Comment by randomtutu** [comment]
I remember the hash value for pcontext is not correct either.
