### ISSUE TITLE
error: class "at::Context" has no member "getCurrentCUDAStream"

### ISSUE THREAD

**Issue by Gjiangtao** [zhanghang1989/PyTorch-Encoding#106]
Hi, I got the error that @tensorDL met before. And like you said,
That is because the PyTorch updates in backend.

Could you change at::Context:: getCurrentCUDAStream to cudaStream_t stream = at::cuda::getCurrentCUDAStream();
Also add #include <ATen/cuda/CUDAContext.h>

and I did every thing what you said, but I
still got the same error. Perhaps I did something wrong. Please tell me the detials which I don’t know to help me to figure this out. Thank you very much！

By the way，my pc environment are：
OS: ubuntu16.04
PyTorch version: master v0.50
Python version: 3.6
CUDA/cuDNN version: cuda9.0+cudnn7.0
GPU models and configuration: GTX1060

**Comment by zhanghang1989** [comment]
If you still have this error, you may miss some parts, change all ``at::Context:: getCurrentCUDAStream`` to ``cudaStream_t stream = at::cuda::getCurrentCUDAStream();``

**Comment by Gjiangtao** [comment]
Thank you for your reply! 
I’m sorry，I think the biggest problem is that I can’t find the words “at::Context:: getCurrentCUDAStream” in my project files. I just found like this:

Targets
    Occurrences of 'getCurrentCUDAStream' in Project
Found Occurrences  (20 usages found)
    Unclassified occurrence  (20 usages found)
        PyTorch-Encoding  (20 usages found)
            build/lib/encoding/lib/gpu  (10 usages found)
                encoding_kernel.cu  (4 usages found)
                    315   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    341   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    364   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    391   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                roi_align_kernel.cu  (2 usages found)
                    378          at::globalContext().getCurrentCUDAStream()>>>(
                    425          at::globalContext().getCurrentCUDAStream()>>>(
                syncbn_kernel.cu  (4 usages found)
                    183   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    217   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    249   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    272   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
            encoding/lib/gpu  (10 usages found)
                encoding_kernel.cu  (4 usages found)
                    315   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    341   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    364   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    391   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                roi_align_kernel.cu  (2 usages found)
                    378          at::globalContext().getCurrentCUDAStream()>>>(
                    425          at::globalContext().getCurrentCUDAStream()>>>(
                syncbn_kernel.cu  (4 usages found)
                    183   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    217   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    249   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();
                    272   cudaStream_t stream = at::globalContext().getCurrentCUDAStream();


Where can I find the words “at::Context:: getCurrentCUDAStream” and change them? _(:з」∠)_

**Comment by Gjiangtao** [comment]
By the way, I have tried to change “at::globalContext().getCurrentCUDAStream()” to “ at::cuda::getCurrentCUDAStream()” or “ at::cuda().getCurrentCUDAStream() or “ at::Context().getCurrentCUDAStream()”

It doesn’t work at all..._(´ཀ`」 ∠)_

**Comment by Gjiangtao** [comment]
您好，我只有一张单卡gtx1060 3g。当我运行命令
`CUDA_VISIBLE_DEVICES=0 python train.py --dataset pcontext --model encnet --aux --se-loss`
报错

> Traceback (most recent call last):
  File "/home/gjt/code/PyTorch-Encoding/experiments/segmentation/train.py", line 178, in <module>
    trainer.training(epoch)
  File "/home/gjt/code/PyTorch-Encoding/experiments/segmentation/train.py", line 108, in training
    outputs = self.model(image)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/models/encnet.py", line 32, in forward
    features = self.base_forward(x)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/models/base.py", line 54, in base_forward
    x = self.pretrained.bn1(x)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/nn/syncbn.py", line 57, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

请问怎么解决这个问题呢？

**Comment by zhanghang1989** [comment]
单卡我没有测过，可能会有问题。单卡就不需要syncBN了，可以试试把所以的batchnorm换成torch.nn.BatchNorm2d

**Comment by Gjiangtao** [comment]
谢谢您的回复，当我按照您的建议换成`torch.nn.BatchNorm2d`后，没有出现之前的错误，但是报出了新的错误：

> Traceback (most recent call last):
  File "/home/gjt/code/PyTorch-Encoding/experiments/segmentation/train.py", line 182, in <module>
    trainer.training(epoch)
  File "/home/gjt/code/PyTorch-Encoding/experiments/segmentation/train.py", line 112, in training
    outputs = self.model(image)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/models/encnet.py", line 32, in forward
    features = self.base_forward(x)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/models/base.py", line 59, in base_forward
    c3 = self.pretrained.layer3(c2)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/dilated/resnet.py", line 93, in forward
    out = self.conv1(x)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 308, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

好像是因为显卡的显存不够了，请问您有什么好的建议吗？

**Comment by zhanghang1989** [comment]
调整batch size，但是会影响收敛效果

**Comment by Gjiangtao** [comment]
谢谢您的回复！
您好，我又遇到一个问题，当我想查看测试结果的图片时，我运行代码
`python test.py --dataset PContext --model-zoo Encnet_ResNet50_PContext `，
结果如下：
![image](https://user-images.githubusercontent.com/31332297/44659429-d13a1280-aa36-11e8-9643-d777be933670.png)
Preprocessing masks 之后生成了一个test.pth文件
然后就报错了：

> Traceback (most recent call last):
  File "experiments/segmentation/test.py", line 124, in <module>
    test(args)
  File "experiments/segmentation/test.py", line 101, in test
    for i, (image, dst) in enumerate(tbar):
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 872, in __iter__
    for obj in iterable:
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 339, in __next__
    return self._process_next_batch(batch)
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 360, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 113, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 113, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/encoding/datasets/pcontext.py", line 75, in __getitem__
    img = Image.open(os.path.join(self.detail.img_folder, path)).convert('RGB')
  File "/home/gjt/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/gjt/.encoding/data/VOCdevkit/VOC2010/JPEGImages/2008_000001.jpg'

VOC2010/JPEGImages/文件夹中没有2008_000001.jpg文件，如图
![image](https://user-images.githubusercontent.com/31332297/44658385-3ab82200-aa33-11e8-9b27-cce928758328.png)
但是从代码生成的index又读取出来了“2008_000001.jpg”这个文件名，导致不能匹配，请问是哪里出了问题呢？

**Comment by zhanghang1989** [comment]
你是不是用的windows？检查一下文件路径吧
