### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'root'

### ISSUE THREAD

**Issue by ByronGe** [zhanghang1989/PyTorch-Encoding#109]
Hi Mr. Zhang:
When I test  model   pascal_voc on  using:
CUDA_VISIBLE_DEVICES=0,1 python train.py --dataset pascal_voc --model encnet --aux --se-loss
 I got the following errors:
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    trainer = Trainer(args)
  File "train.py", line 40, in __init__
    **data_kwargs)
  File "/home/pcx/anaconda3/lib/python3.5/site-packages/encoding/datasets/__init__.py", line 15, in get_segmentation_dataset
    return datasets[name.lower()](**kwargs)
TypeError: __init__() missing 1 required positional argument: 'root

Could you help me solve this problems? Thanks!

**Comment by zhanghang1989** [comment]
1) create your own Dataset similar to ADE20K, set NUM_CLASS to 2
2) add acronyms https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/models/encnet.py#L146
