### ISSUE TITLE
A problem In Installing

### ISSUE THREAD

**Issue by alexalex1234** [zhanghang1989/PyTorch-Encoding#11]
I find this problem in installing 
I use the latest version pytorch and anaconda3
so how can I fix it 
Thank you!

Copying encoding.egg-info to /home/wang/anaconda3/lib/python3.6/site-packages/encoding-0.1.0+c92a7c2-py3.6.egg-info
running install_scripts
Traceback (most recent call last):
  File "test/test.py", line 87, in <module>
    test_scaledL2()
  File "test/test.py", line 42, in test_scaledL2
    test = gradcheck(encoding.functions.scaledL2, input, eps=1e-6, atol=1e-4)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 163, in gradcheck
    output = _differentiable_outputs(func(*inputs))
  File "/home/wang/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 135, in scaledL2
    return _scaledL2.apply(X, C, S)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 95, in forward
    encoding_lib.Encoding_Double_scaledl2_forward(SL, X, C, S)
AttributeError: module 'encoding._ext.encoding_lib' has no attribute 'Encoding_Double_scaledl2_forward'
Traceback (most recent call last):
  File "setup.py", line 64, in <module>
    'install': install,
  File "/home/wang/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wang/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/wang/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 28, in run
    subprocess.check_call("python test/test.py".split())
  File "/home/wang/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'test/test.py']' returned non-zero exit status 1.

**Comment by alexalex1234** [comment]
And has this problem

removing '/home/wang/anaconda3/lib/python3.6/site-packages/encoding-0.1.0+c92a7c2-py3.6.egg-info' (and everything under it)
Copying encoding.egg-info to /home/wang/anaconda3/lib/python3.6/site-packages/encoding-0.1.0+c92a7c2-py3.6.egg-info
running install_scripts
Traceback (most recent call last):
  File "test/test.py", line 87, in <module>
    test_scaledL2()
  File "test/test.py", line 42, in test_scaledL2
    test = gradcheck(encoding.functions.scaledL2, input, eps=1e-6, atol=1e-4)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 133, in gradcheck
    output = func(*inputs)
  File "/home/wang/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 135, in scaledL2
    return _scaledL2.apply(X, C, S)
AttributeError: type object '_scaledL2' has no attribute 'apply'

**Comment by zhanghang1989** [comment]
What is the PyTorch version you are using? Please compile the master branch from source. let me know if you still have the problem

**Comment by alexalex1234** [comment]
I don't have the above problem anymore when I compile the codes.
But I have this problem when I import the module.



Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import encoding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wang/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    import encoding.nn
  File "/home/wang/PyTorch-Encoding/encoding/nn/__init__.py", line 13, in <module>
    from .encoding import *
  File "/home/wang/PyTorch-Encoding/encoding/nn/encoding.py", line 17, in <module>
    from .._ext import encoding_lib
  File "/home/wang/PyTorch-Encoding/encoding/_ext/encoding_lib/__init__.py", line 3, in <module>
    from ._encoding_lib import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'encoding._ext.encoding_lib._encoding_lib'

**Comment by zhanghang1989** [comment]
I guess you are importing the package in the project folder. Just go to another folder

**Comment by zhanghang1989** [comment]
I assume the problem has been solved. If not, feel free to reopen.
