### ISSUE TITLE
train pascal_voc error

### ISSUE THREAD

**Issue by gjm441** [zhanghang1989/PyTorch-Encoding#113]
poor ability of pytorch,when i run the cmd:
"CUDA_VISIBLE_DEVICES=0,1 python train.py --dataset pascal_voc  --model encnet --aux --se-loss"

it comes out error:
Traceback (most recent call last):
  File "train.py", line 176, in <module>
    trainer = Trainer(args)
  File "train.py", line 42, in __init__
    **data_kwargs)
  File "../../build/lib/encoding/datasets/__init__.py", line 15, in get_segmentation_dataset
    return datasets[name.lower()](**kwargs)
TypeError: __init__() missing 1 required positional argument: 'root'
Any help is appreciated.

**Comment by gjm441** [comment]
I find it is a bug, and have fixed it by adding root parameter in train.py.
