### ISSUE TITLE
issues with the "DataParallelCriterion"

### ISSUE THREAD

**Issue by PkuRainBow** [zhanghang1989/PyTorch-Encoding#116]
I employ the DataParallelCriterion like below,

```
    model = DataParallelModel(deeplab)
    model.train()     
    model.float()
    model.cuda()    
    # .......
    criterion = DataParallelCriterion(criterion)
    criterion.cuda()
    cudnn.benchmark = True
```

Then I got such errors inform me an error related the line 163 in your parallel.py

```
Traceback (most recent call last):
  File "train.py", line 160, in <module>
  File "train.py", line 137, in main
    loss = criterion(preds, labels)
  File "/root/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/teamscratch/msravcshare/yuyua/OCNet/utils/parallel.py", line 134, in forward
    outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/teamscratch/msravcshare/yuyua/OCNet/utils/parallel.py", line 188, in _criterion_parallel_apply
    raise output
  File "/teamscratch/msravcshare/yuyua/OCNet/utils/parallel.py", line 163, in _worker
    output = module(*(input + target), **kwargs)
TypeError: can only concatenate list (not "tuple") to list

```

**Comment by tonysy** [comment]
In DataParallelCriterion.forward()

```python
replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
targets = tuple(targets_per_gpu[0] for targets_per_gpu in targets)
outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
```


In _criterion_parallel_apply()

```python
try:
        with torch.cuda.device(device):
                output = module(input, target)
        with lock:
                results[i] = output
except Exception as e:
```
It works for me

**Comment by PkuRainBow** [comment]
@tonysy Have you tested your methods to ensure the performance?
