### ISSUE TITLE
Update with Pytorch Master Branch?

### ISSUE THREAD

**Issue by huanghoujing** [zhanghang1989/PyTorch-Encoding#123]
Hi, I install pytorch (master branch, commit [21ed7e5](https://github.com/pytorch/pytorch/tree/21ed7e51b606f9912b658ab63e016d7546f3b75c)) and torchvision (master branch, commit [4c9c407](https://github.com/pytorch/vision/tree/4c9c40747feae3fead77d06adb0dd60ff9f61710)) from source successfully. Then I install this project from source (master branch, commit [d4e1955](https://github.com/zhanghang1989/PyTorch-Encoding/tree/d4e195538a5cac3a33b9cbde28d54c8ed78a3f91)). When I run command `python experiments/segmentation/test.py --dataset PContext --model-zoo Encnet_ResNet50_PContext --eval`, it gives pytorch error as follows. Help is appreciated! Thanks a lot.

```
Traceback (most recent call last):
  File "experiments/segmentation/test.py", line 16, in <module>
    import encoding.utils as utils
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaledL2, aggregate, pairwise_cosine
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/__init__.py", line 12, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 554, in load
    with_cuda)
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 720, in _jit_compile
    with_cuda=with_cuda)
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 769, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 861, in _build_extension_module
    raise_from(RuntimeError(message), None)
  File "/home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/future/utils/__init__.py", line 454, in raise_from
    raise e
RuntimeError: Error building extension 'enclib_cpu': [1/2] c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include -isystem /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include/TH -isystem /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include/THC -isystem /home/users/houjing.huang/Software/anaconda2/include/python2.7 -fPIC -std=c++11 -c /mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
FAILED: roi_align_cpu.o 
c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include -isystem /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include/TH -isystem /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include/THC -isystem /home/users/houjing.huang/Software/anaconda2/include/python2.7 -fPIC -std=c++11 -c /mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In function 'at::Tensor ROIAlignForwardCPU(const at::Tensor&, const at::Tensor&, int64_t, int64_t, double, int64_t)':
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:407:30: error: 'struct at::Type' has no member named 'tensor'
   auto output = input.type().tensor({num_rois, channels, pooled_height, pooled_width});
                              ^
In file included from /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include/ATen/ATen.h:11:0,
                 from /mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:1:
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:27: error: expected primary-expression before '>' token
       output.data<scalar_t>());
                           ^
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:29: error: expected primary-expression before ')' token
       output.data<scalar_t>());
                             ^
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:27: error: expected primary-expression before '>' token
       output.data<scalar_t>());
                           ^
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:29: error: expected primary-expression before ')' token
       output.data<scalar_t>());
                             ^
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In function 'at::Tensor ROIAlignBackwardCPU(const at::Tensor&, const at::Tensor&, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, double, int64_t)':
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:454:37: error: 'struct at::Type' has no member named 'tensor'
   auto grad_in = bottom_rois.type().tensor({b_size, channels, height, width}).zero_(); 
                                     ^
In file included from /home/users/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/torch/lib/include/ATen/ATen.h:11:0,
                 from /mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:1:
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:28: error: expected primary-expression before '>' token
       grad_in.data<scalar_t>(),
                            ^
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:30: error: expected primary-expression before ')' token
       grad_in.data<scalar_t>(),
                              ^
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:28: error: expected primary-expression before '>' token
       grad_in.data<scalar_t>(),
                            ^
/mnt/data-1/data/houjing.huang/Software/anaconda2/lib/python2.7/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:30: error: expected primary-expression before ')' token
       grad_in.data<scalar_t>(),
                              ^
ninja: build stopped: subcommand failed.


```

**Comment by zhanghang1989** [comment]
I haven't updated PyTorch for a while. Let me test it and get back to you.

**Comment by huanghoujing** [comment]
Thanks a lot! I suggest you provide the Pytorch commit (in README) you are working with each time you update your code.

**Comment by kmaninis** [comment]
Hi, thanks for the awesome sync batchnorm.  I am having the same exact issue when importing encoding. Just updated to the latest PyTorch version (the one of the comment above).
