### ISSUE TITLE
_ZN2at4cuda20getCurrentCUDAStreamEv

### ISSUE THREAD

**Issue by TensorDL** [zhanghang1989/PyTorch-Encoding#127]
>>> import encoding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets, optimizer
  File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/lib/__init__.py", line 25, in <module>
    ], build_directory=gpu_path, verbose=False)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 494, in load
    with_cuda=with_cuda)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 670, in _jit_compile
    return _import_module_from_library(name, build_directory)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 753, in _import_module_from_library
    return imp.load_module(module_name, file, path, description)
  File "/usr/local/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
**ImportError: /media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/lib/gpu/enclib_gpu.so: undefined symbol: _ZN2at4cuda20getCurrentCUDAStreamEv**

**Comment by zhanghang1989** [comment]
Could you please pull the most recent version of this package or try:
```bash
pip install torch-encoding --upgrade
```

**Comment by TensorDL** [comment]
In the table, EncNet_ResNet50_ADE achieves 80.1 pixAcc and 41.5 mIoU (https://hangzhang.org/PyTorch-Encoding/experiments/segmentation.html). However, the corresponding log file shows it obtains 78.0 pixAcc and 40.2 mIoU.

**Comment by zhanghang1989** [comment]
1. The performance get improved after paper publication.
2. The log file is out-of-date.
3. The validation score in the log file only uses center crops, which is used for monitoring the training process. For correct evaluation, please use `test.py`

**Comment by zhanghang1989** [comment]
For the command reproducing the results, please click the `cmd` button.

**Comment by qiulesun** [comment]
**Question 1**:
I realized that the 7x7 conv. layer in original Resnet50 is replaced with three 3x3 conv. ones. The modified Resnet50 is then trained on the ImageNet2012 as backbone for further finetuning?

**Comment by qiulesun** [comment]
**Question 1**:
I realized that the 7x7 conv. layer in original Resnet50 is replaced with three 3x3 conv. ones. Is the modified Resnet50 then trained from scratch on the ImageNet2012 as backbone for further finetuning?

**Comment by qiulesun** [comment]
**Question 1**:
I realized that the 7x7 conv. layer in original Resnet50 is replaced with three 3x3 conv. ones. Is the modified Resnet50 then trained from scratch on the ImageNet2012 as backbone for further finetuning?

**Comment by qiulesun** [comment]
**Question 1**:
I realized that the 7x7 conv. layer in original Resnet50 is replaced with three 3x3 conv. ones. Is the modified Resnet50 then trained from scratch on the ImageNet2012 as backbone for further finetuning?

**Comment by qiulesun** [comment]
**the effectiveness of SyncBN**
I hold the view that you have  systematically evaluated the effectiveness of the proposed SyncBN. Could you show results compared with standard BN (or Group Norm if possible) on Imagenet2012 or segmentation datasets you have done ?

**Comment by qiulesun** [comment]
**ablation study**
I understand that. However, unfortunately I can't see how much SyncBN works from the CVPR18 paper. Given the same batchsize (e.g., 16), do you have ablation experimental results to illustrate the effectiveness of  SyncBN compared with other BN on segmentation dataset?

**Comment by zhanghang1989** [comment]
Hi @qiulesun , thanks for interest in this work.

I do have a table in the paper supplementary material for benchmarking SyncBN on Pascal Context dataset:

 method              BN                pixAcc, mIoU
1. FCN (4 GPUs) standard BN  47.7, 20.8
2. FCN                 fixed BN         72.5, 40.5
3. FCN                 sync BN         73.4, 41.0

**Comment by qiulesun** [comment]
**supplementary material**
The results is meaningful. But I do not find the supplementary material in your homepage and CVPR 2018 open access (http://openaccess.thecvf.com/CVPR2018_search.py). Could you show the link to downlond it?

**Comment by qiulesun** [comment]
Thank you! My email address is qiulesun@163.com

**Comment by qiulesun** [comment]
**setting of workers**
I'm sorry for bother you again. Should workers be equal to the batch size in option script? Or to the number of CPU cores in my machine? Or to the number of GPUs? Is there a guidelines for assigning workers ?

**Comment by zhanghang1989** [comment]
1. I usually set the number of workers as 16 (same as batch size). But it also depends on your cpu.
2. I will release the training and test on cityscapes later.

**Comment by qiulesun** [comment]
**trivial question**
1. I want to get results on PContext with backgroud, i,e,. 60 classes. Where do I modify the code to achieve that?

**Comment by zhanghang1989** [comment]
The background IoU is considered as 0. Then the mIoU over 60 classes is equal to `mIoU_59 * 59 / 60`

**Comment by qiulesun** [comment]
**training command**
I notice that you have achievd the deeplab_v3 in your awesome and constantly developing repo. Could you mind providing the training commands to train deeplab_v3.

**Comment by qiulesun** [comment]
**EncNet_ResNet101_ADE**
It is an awesome and developing repo. containing more SOTA methods.
I notice that the basesize and cropsize are only set to 640 and 576, respectively, for training encnet using resnet101 on ADE20K. I am wondering why you only did this.

**Comment by qiulesun** [comment]
It is an awesome and developing repo. containing more SOTA methods.
Question 1
For multisize evaluation, will you consider employing dense crop on feature map rather than on input image? It may further boost the performance.
Question 2
Do you consdier the usage of accumulation gradient strategy to update param. due to limited GPU memory?

**Comment by kernel-Peanut** [comment]
> I use the released code without problem before updating. Now, I notice that the codes are updated newly. So I can not wait to try it, and successfully run the python setup.py install. Then when I run the import encoding, I get the error like this.
> 
> **>>> import encoding**
> Traceback (most recent call last):
> File "", line 1, in 
> File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/**init**.py", line 13, in 
> from . import nn, functions, dilated, parallel, utils, models, datasets, optimizer
> File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/nn/**init**.py", line 12, in 
> from .encoding import *
> File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in 
> from ..functions import scaled_l2, aggregate, pairwise_cosine
> File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/functions/**init**.py", line 2, in 
> from .encoding import *
> File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/functions/encoding.py", line 14, in 
> from .. import lib
> File "/media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/lib/**init**.py", line 25, in 
> ], build_directory=gpu_path, verbose=False)
> File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 494, in load
> with_cuda=with_cuda)
> File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 670, in _jit_compile
> return _import_module_from_library(name, build_directory)
> File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 753, in _import_module_from_library
> return imp.load_module(module_name, file, path, description)
> File "/usr/local/anaconda3/lib/python3.6/imp.py", line 243, in load_module
> return load_dynamic(name, filename, file)
> File "/usr/local/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
> return _load(spec)
> **ImportError: /media/rudycv/SSD500G/pytorch_dir/PyTorch-Encoding-Updated/PyTorch-Encoding/encoding/lib/gpu/enclib_gpu.so: undefined symbol: _ZN2at4cuda20getCurrentCUDAStreamEv**

I meet the same error with you ,how do you solve it? Just to get the latest torch-encoding cannot fix it
