### ISSUE TITLE
Encoding folder

### ISSUE THREAD

**Issue by kimchicanh** [zhanghang1989/PyTorch-Encoding#13]
Hi,

Thank for your project. I have confuse with encoding folder in your project.
When I build setup.py, it run test.py in test folder and it will run function in encoding folder, but encoding folder in python3.5. It will have error and I do not understand why your project have encoding folder but it do not install in it:
Testing scaledL2(): True
Traceback (most recent call last):
  File "test/test.py", line 88, in <module>
    test_encoding() 
  File "test/test.py", line 52, in test_encoding
    test = gradcheck(layer, input, eps=1e-6, atol=1e-4)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/gradcheck.py", line 154, in gradcheck
    output = func(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/encoding/nn/encoding.py", line 97, in forward
    A = F.softmax(scaledL2(X, self.codewords, self.scale), dim=2)
TypeError: softmax() got an unexpected keyword argument 'dim'

Thanks

**Comment by zhanghang1989** [comment]
Your PyTorch is out of date. Please use master branch https://github.com/pytorch/pytorch

**Comment by kimchicanh** [comment]
Thanks for your support

**Comment by zhanghang1989** [comment]
I am closing it, but feel free to reopen if you still have troubles.
