### ISSUE TITLE
call function encoding.nn.BatchNorm2d error

### ISSUE THREAD

**Issue by zhFuECL** [zhanghang1989/PyTorch-Encoding#131]
Here is my env in conda
```
channels:
  - pytorch
  - serge-sans-paille
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py27_1
  - cffi=1.11.5=py27he75722e_1
  - cython=0.28.5=py27hf484d3e_0
  - intel-openmp=2019.0=118
  - isl=0.12.2=0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py27h7dd41cf_0
  - mkl_random=1.0.1=py27h4414c95_1
  - mpc=1.0.3=hf803216_4
  - mpfr=3.1.5=h12ff648_1
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py27h6bb024c_1
  - numpy=1.15.2=py27h1d66e8a_1
  - numpy-base=1.15.2=py27h81de0dd_1
  - openssl=1.0.2p=h14c3975_0
  - pip=10.0.1=py27_0
  - pycparser=2.19=py27_0
  - python=2.7.15=h1571d57_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.4.3=py27_0
  - sqlite=3.25.2=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.32.0=py27_0
  - zlib=1.2.11=ha838bed_2
  - pytorch-nightly=1.0.0.dev20181004=py2.7_cuda9.0.176_cudnn7.1.2_0
  - cloog=0.18.1=1
  - gcc_49=4.9.1=6
  - gmp=5.1.3=0
  - pip:
    - chardet==3.0.4
    - idna==2.7
    - nose==1.3.7
    - pillow==5.3.0
    - requests==2.19.1
    - scipy==1.1.0
    - torch==1.0.0.dev20181004
    - torch-encoding==0.5.2
    - tqdm==4.26.0
    - urllib3==1.23
```
and the error log, could help me figure out what happened here?

```
Traceback (most recent call last):
  File "./models_fix/a.py", line 296, in <module>
    a = model(torch.randn(1, 3, 96, 96).cuda())
  File "/home/mata/anaconda2/envs/pt-pre/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "./models_fix/a.py", line 29, in forward
    out = self.bn(out)
  File "/home/mata/anaconda2/envs/pt-pre/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mata/anaconda2/envs/pt-pre/lib/python2.7/site-packages/encoding/nn/syncbn.py", line 57, in forward
    mean, inv_std = self._slave_pipe.run_slave(_ChildMessage(xsum, xsqsum, N))
AttributeError: 'NoneType' object has no attribute 'run_slave'

```

**Comment by zhFuECL** [comment]
https://github.com/zhanghang1989/PyTorch-Encoding/issues/75
