### ISSUE TITLE
Need to old version

### ISSUE THREAD

**Issue by fip-lab** [zhanghang1989/PyTorch-Encoding#136]
Hi, is there an old version of encoding? because the project to run depends on your old version of encoding, the current version does not support.

**Comment by fip-lab** [comment]
Traceback (most recent call last):
  File "train_mobile.py", line 16, in <module>
    from models.rfmobilenetv2plus import RFMobileNetV2Plus
  File "/home/dl/LightNet-master/test/models/rfmobilenetv2plus.py", line 6, in <module>
    from modules import SCSEBlock, InPlaceABN, InPlaceABNWrapper, RFBlock
  File "/home/dl/LightNet-master/test/modules/__init__.py", line 1, in <module>
    from .misc import GlobalAvgPool2d, CatInPlaceABN, ModifiedSCSEBlock, SCSEBlock, SEBlock, LightHeadBlock, VortexPooling
  File "/home/dl/LightNet-master/test/modules/misc.py", line 3, in <module>
    from .bn import ABN
  File "/home/dl/LightNet-master/test/modules/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/dl/LightNet-master/test/modules/functions.py", line 5, in <module>
    from . import _ext
  File "/home/dl/LightNet-master/test/modules/_ext/__init__.py", line 3, in <module>
    from torch.utils.cpp_extension import _wrap_function
ImportError: cannot import name '_wrap_function'

pytorch 1.0.0

**Comment by fip-lab** [comment]
> Hi, is there an old version of encoding? because the project to run depends on your old version of encoding, the current version does not support.

need support pytorch version = 0.3.0

**Comment by my462** [comment]
try pip install torch-encoding==

**Comment by zhanghang1989** [comment]
Now support PyTorch stable 1.0 https://github.com/zhanghang1989/PyTorch-Encoding/pull/156

**Comment by zhanghang1989** [comment]
Sorry that we don’t support older versions. I will try to keep the package compatible with the latest master branch.

**Comment by Rutherford1895** [comment]
Hi, I found a similar issue. 

The tutorial on this page (https://hangzhang.org/PyTorch-Encoding/experiments/texture.html) includes a test of the pre-trained model on MINC-2500, but the  line
`python main.py --dataset minc --model deepten_resnet50_minc --nclass 23  --pretrained --eval`
doesn't work anymore. Specifically, it might be because of a change made in

PyTorch-Encoding/encoding/datasets/minc.py,

where in class MINCDataset, the __init__() no longer has 'train' and 'download' parameters.

I understand it is difficult to maintain every script in a large package, nevertheless I would appreciate if those no longer supported functions could be highlighted in a README file under the same folder.

Thanks
