### ISSUE TITLE
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by sanersbug** [zhanghang1989/PyTorch-Encoding#143]
windows , python3.5, torch 0.4.1 (anyone install successfully in windows?)

when i run python3 download_models.py 

 it shows like follow
D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:92: UserWarning: Err
or checking compiler version: [WinError 2] 系统找不到指定的文件。
  warnings.warn('Error checking compiler version: {}'.format(error))
D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:118: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
信息: 用提供的模式无法找到文件。
Traceback (most recent call last):
  File "download_models.py", line 2, in <module>
    import encoding
  File "D:\anaconda3\lib\site-packages\encoding\__init__.py", line 13, in <modul
e>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "D:\anaconda3\lib\site-packages\encoding\nn\__init__.py", line 12, in <mo
dule>
    from .encoding import *
  File "D:\anaconda3\lib\site-packages\encoding\nn\encoding.py", line 18, in <mo
dule>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "D:\anaconda3\lib\site-packages\encoding\functions\__init__.py", line 2,
in <module>
    from .encoding import *
  File "D:\anaconda3\lib\site-packages\encoding\functions\encoding.py", line 14,
 in <module>
    from .. import lib
  File "D:\anaconda3\lib\site-packages\encoding\lib\__init__.py", line 15, in <m
odule>
    ], build_directory=cpu_path, verbose=False)
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 514,
in load
    with_cuda=with_cuda)
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 678,
in _jit_compile
    with_cuda=with_cuda)
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 860,
in _write_ninja_file
    'cl']).decode().split('\r\n')
  File "D:\anaconda3\lib\subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "D:\anaconda3\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit
status 1

Any advice? thanks very much

**Comment by zhanghang1989** [comment]
This does not work with PyTorch 0.4.1. Please use PyTorch 1.0

**Comment by sanersbug** [comment]
@zhanghang1989 thank you very much ! I  will try it

**Comment by ksnzh** [comment]
@sanersbug You can go to `https://github.com/peterjc123/pytorch-scripts` for help.

**Comment by MrAugust1217** [comment]
I update the pytorch from 0.4.1to 1.0.0,but it do not work 

`import encoding
Traceback (most recent call last):
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/__init__.py", line 15, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'enclib_cpu': [1/6] c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/ouc-29/anaconda3/envs/wangzhe/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
FAILED: roi_align_cpu.o 
c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/ouc-29/anaconda3/envs/wangzhe/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:1:10: fatal error: torch/tensor.h: No such file or directory
 #include <torch/tensor.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
[2/6] c++ -MMD -MF syncbn_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/ouc-29/anaconda3/envs/wangzhe/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/syncbn_cpu.cpp -o syncbn_cpu.o
FAILED: syncbn_cpu.o 
c++ -MMD -MF syncbn_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/ouc-29/anaconda3/envs/wangzhe/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/syncbn_cpu.cpp -o syncbn_cpu.o
/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/syncbn_cpu.cpp:1:10: fatal error: torch/tensor.h: No such file or directory
 #include <torch/tensor.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
[3/6] c++ -MMD -MF nms_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/ouc-29/anaconda3/envs/wangzhe/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/nms_cpu.cpp -o nms_cpu.o
FAILED: nms_cpu.o 
c++ -MMD -MF nms_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/ouc-29/anaconda3/envs/wangzhe/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/nms_cpu.cpp -o nms_cpu.o
/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/nms_cpu.cpp:1:10: fatal error: torch/tensor.h: No such file or directory
 #include <torch/tensor.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
[4/6] c++ -MMD -MF encoding_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/ouc-29/anaconda3/envs/wangzhe/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/encoding_cpu.cpp -o encoding_cpu.o
[5/6] c++ -MMD -MF operator.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/ouc-29/anaconda3/envs/wangzhe/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/operator.cpp -o operator.o
In file included from /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/operator.h:1:0,
                 from /home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/encoding/lib/cpu/operator.cpp:1:
/home/ouc-29/anaconda3/envs/wangzhe/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^~~~~~~
ninja: build stopped: subcommand failed.
`

**Comment by MrAugust1217** [comment]
@zhanghang1989 I update the pytorch from 0.4.1to 1.0.0,but it do not work

**Comment by flyingshan** [comment]
@zhanghang1989 have the same problem,too~
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit  status 1
python3.5, pytorch1.0, no cuda

**Comment by pribadihcr** [comment]
Is this pytorch 0.4.1 of windows issue has been resolved ?. Got similar problem

**Comment by zhanghang1989** [comment]
Please use PyTorch stable 1.0. 
Sorry that we are not supporting older versions, because it is hard to support multiple versions.

**Comment by liuky74** [comment]
> Please use PyTorch stable 1.0.
> Sorry that we are not supporting older versions, because it is hard to support multiple versions.

I update the pytorch to 1.0.1 but it still can't work

**Comment by Fariha1123** [comment]
I am using cuda 10.0, pytorch 1.1.0, python 3.6.7, and fall into the same error, does any one know the fix?

**Comment by deepwormm** [comment]
using pytorch1.31 with python3.6.0. same error.

**Comment by ksnzh** [comment]
@deepwormm go to use PyTorch >= 1.0 with original Distributed DataParallel support

**Comment by ygjwd12345** [comment]
pytorch 1.4 is also have this problem
