### ISSUE TITLE
error when install encoding package

### ISSUE THREAD

**Issue by jind11** [zhanghang1989/PyTorch-Encoding#15]
hi, I am now working on a segmentation project so I do need this package to solve the batch norm and uneven data parallel problems. However, I encountered this error when I installed the package in python3.5 env:
Testing scaledL2(): True
Traceback (most recent call last):
  File "test/test.py", line 88, in <module>
    test_encoding() 
  File "test/test.py", line 52, in test_encoding
    test = gradcheck(layer, input, eps=1e-6, atol=1e-4)
  File "/scratch/jindi/.condaEnvs/python3/lib/python3.5/site-packages/torch/autograd/gradcheck.py", line 154, in gradcheck
    output = func(*inputs)
  File "/scratch/jindi/.condaEnvs/python3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch/jindi/.condaEnvs/python3/lib/python3.5/site-packages/encoding/nn/encoding.py", line 97, in forward
    A = F.softmax(scaledL2(X, self.codewords, self.scale), dim=1)
TypeError: softmax() got an unexpected keyword argument 'dim'
Could you help solve this installment problem? Thanks!

**Comment by zhanghang1989** [comment]
PyTorch our of date. Please use master branch.

**Comment by maomaodog** [comment]
I also have some installation error. My env is python 2.7:
removing '/home/zzx/INSTALL/conda2/lib/python2.7/site-packages/encoding-0.1.0+01946d4-py2.7.egg-info' (and everything under it)
Copying encoding.egg-info to /home/zzx/INSTALL/conda2/lib/python2.7/site-packages/encoding-0.1.0+01946d4-py2.7.egg-info
running install_scripts
Traceback (most recent call last):
  File "test/test.py", line 11, in <module>
    import encoding
  File "/home/zzx/INSTALL/conda2/lib/python2.7/site-packages/encoding/__init__.py", line 13, in <module>
    import encoding.nn
  File "/home/zzx/INSTALL/conda2/lib/python2.7/site-packages/encoding/nn/__init__.py", line 11, in <module>
    from .encoding import *
  File "/home/zzx/INSTALL/conda2/lib/python2.7/site-packages/encoding/nn/encoding.py", line 19, in <module>
    from ..parallel import my_data_parallel
  File "/home/zzx/INSTALL/conda2/lib/python2.7/site-packages/encoding/parallel.py", line 259
    return (modules[0](*inputs[0], *targets[0], **kwargs_tup[0]), )
                                   ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    'install': install,
  File "/home/zzx/INSTALL/conda2/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/zzx/INSTALL/conda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/zzx/INSTALL/conda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/zzx/INSTALL/conda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 26, in run
    subprocess.check_call("python test/test.py".split())
  File "/home/zzx/INSTALL/conda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'test/test.py']' returned non-zero exit status 1
zzx@ubuntu:~/INSTALL/PyTorch-Encoding$ cd ..
zzx@ubuntu:~/INSTALL$ ls

**Comment by zhanghang1989** [comment]
Please use Python 3. Anaconda 3 preferred.

**Comment by maomaodog** [comment]
Installation is complete. But can we see some sample code about how to use these modules?  Thanks !

**Comment by maomaodog** [comment]
Hi ! This module has been successfully installed. But after I checked the experiment code. It seems that you guys haven't given a sample code how this synchronized batch normalization module work. Can you please show us how it works?

**Comment by maomaodog** [comment]
It looks like that modules in the libaray are not available yet? There is no such module in there:

ModuleNotFoundError: No module named 'encoding.parallel.SelfDataParalle'; 'encoding.parallel' is not a package

**Comment by zhanghang1989** [comment]
import encoding

**Comment by EmmaW8** [comment]
I solved this problem by uninstall the pytorch-encoding and then copy the encoding folder in the repo to the annoconda3 site-pachkages.

```
pip uninstall pytorch-encoding
cp -r DANet/encoding software/anaconda3/envs/pytorch3_cuda9/lib/python3.7/site-packages/
```
