### ISSUE TITLE
ImportError: No module named 'enclib_cpu'

### ISSUE THREAD

**Issue by flyingshan** [zhanghang1989/PyTorch-Encoding#153]
When I import encoding module, an error occurs:
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import encoding
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\nn\__init__.py", line 12, in <module>
    from .encoding import *
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\nn\encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\functions\__init__.py", line 2, in <module>
    from .encoding import *
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\functions\encoding.py", line 14, in <module>
    from .. import lib
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\lib\__init__.py", line 15, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 645, in load
    is_python_module)
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 964, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'enclib_cpu'
>>> import encoding
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import encoding
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\nn\__init__.py", line 12, in <module>
    from .encoding import *
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\nn\encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\functions\__init__.py", line 2, in <module>
    from .encoding import *
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\functions\encoding.py", line 14, in <module>
    from .. import lib
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\encoding\lib\__init__.py", line 15, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 645, in load
    is_python_module)
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py", line 964, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Users\ys\AppData\Local\Programs\Python\Python36\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'enclib_cpu'

My pytorch version is 1.0stable ,cuda version 9.0, python 3.6 would somebody help me solve this problem?

**Comment by YLONl** [comment]
Anybody solved this error?
