### ISSUE TITLE
Subprocess.CalledProcessError:Command '['ninja','-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by zhenxingsh** [zhanghang1989/PyTorch-Encoding#161]
the environment configure:
pytorch: 1.0.0
python:3.6.7
ubuntu:16.04
Anaconda3

when i run python and import encoding,it could appeare below errors. 
$python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.0.0
>>> import encoding
Traceback (most recent call last):
  File "/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
**subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data_2/pytorch_project/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/data_2/pytorch_project/PyTorch-Encoding/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/data_2/pytorch_project/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/data_2/pytorch_project/PyTorch-Encoding/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/data_2/pytorch_project/PyTorch-Encoding/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/data_2/pytorch_project/PyTorch-Encoding/encoding/lib/__init__.py", line 27, in <module>
    build_directory=gpu_path, verbose=False)
  File "/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'enclib_gpu': [1/7] /usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
FAILED: syncbn_kernel.cuda.o 
/usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00003cd1_00000000-7_syncbn_kernel.cpp1.ii".
[2/7] /usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/encodingv2_kernel.cu -o encodingv2_kernel.cuda.o
FAILED: encodingv2_kernel.cuda.o 
/usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/encodingv2_kernel.cu -o encodingv2_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00003cd0_00000000-7_encodingv2_kernel.cpp1.ii".
[3/7] /usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
FAILED: nms_kernel.cuda.o 
/usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00003cd3_00000000-7_nms_kernel.cpp1.ii".
[4/7] /usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/encoding_kernel.cu -o encoding_kernel.cuda.o
FAILED: encoding_kernel.cuda.o 
/usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/encoding_kernel.cu -o encoding_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00003cce_00000000-7_encoding_kernel.cpp1.ii".
[5/7] /usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/roi_align_kernel.cu -o roi_align_kernel.cuda.o
FAILED: roi_align_kernel.cuda.o 
/usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/roi_align_kernel.cu -o roi_align_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00003cd2_00000000-7_roi_align_kernel.cpp1.ii".
[6/7] /usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/activation_kernel.cu -o activation_kernel.cuda.o
FAILED: activation_kernel.cuda.o 
/usr/local/cuda-8.0/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/TH -isystem /data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda-8.0/include -isystem /data_2/Anaconda3/envs/pytorch1.0.0/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /data_2/pytorch_project/PyTorch-Encoding/encoding/lib/gpu/activation_kernel.cu -o activation_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/data_2/Anaconda3/envs/pytorch1.0.0/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00003ccc_00000000-7_activation_kernel.cpp1.ii".
ninja: build stopped: subcommand failed.

**Comment by YangWangsky** [comment]
I met the same situation and got the same warning.
While I used torch-nightly (1.0.0.dev20181020) and torch-encoding (0.5.2), it was ok.

**Comment by MrAugust1217** [comment]
@YangWangsky Where can I find pytorch-encoding 0.5.2?

**Comment by MrAugust1217** [comment]
@zhanghang1989 by the way,when I use the"pip install torch-encoding",but can not find it

**Comment by zhengnianqing** [comment]
I get the same error,It has troubles me several days,Does anyone have the proper solution?

**Comment by xd17** [comment]
将encodoing_kernel.cu    nms_kernel.cu   activation_kernel.cu 的‘#include<torch/extension.h>’ 换成
‘#include <torch/serialize/tensor.h>’
在operation.h中添加 ‘#include <torch/serialize/tensor.h>’
问题应该能够解决

**Comment by YangWangsky** [comment]
> @YangWangsky Where can I find pytorch-encoding 0.5.2?

You could get the file from the following url.
https://pypi.org/project/torch-encoding/#history

**Comment by eitanrich** [comment]
> 将encodoing_kernel.cu nms_kernel.cu activation_kernel.cu 的‘#include<torch/extension.h>’ 换成
> ‘#include <torch/serialize/tensor.h>’
> 在operation.h中添加 ‘#include <torch/serialize/tensor.h>’
> 问题应该能够解决

I followed this suggestion (I think...), but did the same in all cu files in encoding/lib/gpu. The error seemed to go away. :)

**Comment by developpeur3d** [comment]
If you are wondering where are the files to be modified , here is the path :
C:\.......\......\PyTorch-Encoding\encoding\lib\gpu

**Comment by XRSWATER** [comment]
> I met the same situation and got the same warning.
> While I used torch-nightly (1.0.0.dev20181020) and torch-encoding (0.5.2), it was ok.

Hi, sorry to bother you, can you share the packages of torch-nightly(1.0.0.dev20181020) with me? I can't find the package in official website. My email is: 513221837@qq.com

**Comment by Gmgge** [comment]
@developpeur3d sorry to bother you.Are you building on windows?

**Comment by XRSWATER** [comment]
No， I use Linux because Windows failed to run the code.






------------------ Original ------------------

**Comment by Fariha1123** [comment]
I am on windows, is the fix same for that?

**Comment by XRSWATER** [comment]
Sorry, I don’t know. I finally used linux to solve the problem.&nbsp;

发自我的iPhone


------------------ Original ------------------

**Comment by twister1606** [comment]
Traceback (most recent call last):
File "eval.py", line 185, in
main()
File "eval.py", line 86, in main
model = neurvps.models.VanishingNet(
File "C:\Users\Dimple\neurvps\neurvps\models\vanishing_net.py", line 23, in init
self.anet = ApolloniusNet(output_stride, upsample_scale)
File "C:\Users\Dimple\neurvps\neurvps\models\vanishing_net.py", line 90, in init
self.conv00 = ConicConv(32, 32)
File "C:\Users\Dimple\neurvps\neurvps\models\conic.py", line 12, in init
self.deform_conv = DeformConv(
File "C:\Users\Dimple\neurvps\neurvps\models\deformable.py", line 132, in init
DCN = load_cpp_ext("DCN")
File "C:\Users\Dimple\neurvps\neurvps\models\deformable.py", line 24, in load_cpp_ext
ext = load(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 986, in load
return _jit_compile(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1193, in _jit_compile
_write_ninja_file_and_build_library(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1285, in _write_ninja_file_and_build_library
_write_ninja_file_to_build_library(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1679, in _write_ninja_file_to_build_library
_write_ninja_file(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1790, in _write_ninja_file
cl_paths = subprocess.check_output(['where',
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\subprocess.py", line 411, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args, output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Got this error while working on this project: https://github.com/zhou13/neurvps
Please help us resolve it ASAP
