### ISSUE TITLE
no module named enclib_gpu

### ISSUE THREAD

**Issue by marshallwu1** [zhanghang1989/PyTorch-Encoding#163]
Hi,author. I have followed the instructions on your page. I installed PyTorch1.0 and do PIP INstall torch-encoding. Then I got your code by git clone, and run "python setup.py install" with no errors. But when I run "python scripts/prepare_pascal.py" or "import encoding", I got the error like this. It seems that the "enclib_gpu" cannot be built.

> >>> import encoding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "encoding/nn/encoding.py", line 19, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "encoding/lib/__init__.py", line 27, in <module>
    build_directory=gpu_path, verbose=False)
  File "/home/wmx4/anaconda3/envs/pytorch1.0/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/wmx4/anaconda3/envs/pytorch1.0/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/wmx4/anaconda3/envs/pytorch1.0/lib/python2.7/site-packages/torch/utils/cpp_extension.py", line 964, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
ImportError: No module named enclib_gpu

The version of PyTorch is 1.0, python 2.7, cuda9.0, and I also installed ninja 1.8.2.

**Comment by henanjun** [comment]
same problem.  The version of pytorch is 1.0, python 3.6, cuda 8.0, ninja 1.8.2.  Ubuntu 16.04.5.
I am wondering if I need I try cuda 9.0

**Comment by henanjun** [comment]
> Please try using CUDA 9.2 and let me know if you still have the problem.

Thank you very much. I solved the problem by re-installing CUDA 9.2.

**Comment by huanghoujing** [comment]
@marshallwu1 Do you still have problem with installation? I find it necessary to
- install pytorch 1.0 from source. This is to avoid `Segmentation Fault (core dumped)` error, in my trial.
- modify some include clauses of Pytorch-Encoding. This is learnt from [this issue](https://github.com/zhanghang1989/PyTorch-Encoding/issues/161).

My installation guide is [this](https://github.com/huanghoujing/PyTorch-Encoding/blob/master/Install_Prerequisite_for_Pytorch_Encoding.md) and then [this](https://github.com/huanghoujing/PyTorch-Encoding/blob/master/Fix_Bugs_of_Pytorch_Encoding.md).
