### ISSUE TITLE
Errors of 'import encoding' on pytorch==1.0.0 for all versions of pytorch-encoding.

### ISSUE THREAD

**Issue by Nyquist0** [zhanghang1989/PyTorch-Encoding#174]
Hi, Dr.  @zhanghang1989 
I use 'pip install torch==1.0.0' and 'pip install torch-encoding==1.0.0'. 
The ninja version is 1.8.2, and the cuda version is 9.0.0.
But when I type "import encoding", it raises the error as follow(The characters of original errors are too many to paste, so I paste part of the errors, and highlight the key part.). Do you know why 'pip install' raises these errors? 

>>> import encoding
Traceback (most recent call last):
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
**subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.**
**During handling of the above exception, another exception occurred:**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/encoding/lib/__init__.py", line 27, in <module>
    build_directory=gpu_path, verbose=False)
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
**RuntimeError: Error building extension 'enclib_gpu': [1/8] c++ -MMD -MF operator.o.d -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem** /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/lib/include -isystem /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/cgv841/anaconda3/envs/seg-torch/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/encoding/lib/gpu/operator.cpp -o operator.o
[2/8] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/lib/include -isystem /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/cgv841/anaconda3/envs/seg-torch/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/cgv841/anaconda3/envs/seg-torch/lib/python3.6/site-packages/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
FAILED: nms_kernel.cuda.o 
...
ninja: build stopped: subcommand failed.

I have tried the other version of torch-encoding(1.0.1, 1.0.0, 0.5.2, 0.4.5), and it doesn't work all.

**Comment by zhanghang1989** [comment]
Sorry about the error you are experiencing.

This tutorial is a sucessful setup example for AWS EC2 p3 instance with ubuntu 16.04, CUDA 9.2.
We cannot guarantee it to work for all the machines, but the steps should be similar.
Assuming CUDA and cudnn are already sucessfully installed, otherwise please refer to other tutorials.

      * Install Anaconda from the `link <https://www.anaconda.com/distribution/>`_, and install python 3.6.5::

         conda install python==3.6.5

      * Install ninja::
 
         wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
         sudo unzip ninja-linux.zip -d /usr/local/bin/
         sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force

      * Install PyTorch::

         conda install -c pytorch magma-cuda92
         conda install pytorch torchvision cudatoolkit=92 -c pytorch

      * Install this package::

         pip install torch-encoding

**Comment by zhanghang1989** [comment]
Just an update. CUDA toolkit 10.0 fix the problem. 
That is because of the higher version of pytorch pre-build binary.

**Comment by NseaBlu** [comment]
Hi, Dr. @zhanghang1989
I also have this problem. I change  CUDA version ,the CUDA version is 10.1,but it doesn't work.

**Comment by minkee77** [comment]
try
`conda uninstall pytorch
pip install https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
pip install torchvision`

**Comment by minkee77** [comment]
try
`conda uninstall pytorch`
`pip install https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl`
`pip install torchvision`

**Comment by Nyquist0** [comment]
Dr. @zhanghang1989 
Thx for your help. And I found the problem is the version of pytorch. 
It didn't work to use `pip install torch` because there is something wrong with the source of pip in China.
Using `git clone --recursive https://github.com/pytorch/pytorch`
Then the problem will be solved.
Thx again.

**Comment by Gmgge** [comment]
hi,@Nyquist0
What version is your pytorch? Have you upgraded your cuda?.I installed it from the whl file, but I have the same error.
look forward to your reply.

**Comment by Gmgge** [comment]
hi,@Nyquist0
Sorry to bother you, I just solved the problem.

**Comment by Nemasery** [comment]
> hi,@Nyquist0
> Sorry to bother you, I just solved the problem.

How did you solve the follow error?
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by Gmgge** [comment]
@Nemasery,
你的pytorch=1.0.0和cuda=10.0吗？ninja是否成功安装呢？linux or windows？ 刚才我在全新环境下安装了一次，并没有出现此错误。

**Comment by Nemasery** [comment]
我的pytorch1.0.1 cuda10 ninjia1.8.2

Gmgge <notifications@github.com> 于 2019年4月11日周四 09:35写道：
