### ISSUE TITLE
Issue with syncbn

### ISSUE THREAD

**Issue by iliadsouti** [zhanghang1989/PyTorch-Encoding#18]
Thank you for your effort. I got an error while running a model in syncbn.py. I don't know have any clue about solving this. Can you help me out. Here is the error:
Traceback (most recent call last):
    loss.backward()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/encoding/functions/syncbn.py", line 102, in backward
    self.training) 
NameError: name 'self' is not defined

**Comment by zhanghang1989** [comment]
That is a typo, change `self` to `ctx`
https://github.com/zhanghang1989/PyTorch-Encoding/blob/master/encoding/functions/syncbn.py#L102

**Comment by zhanghang1989** [comment]
I am closing it. It will be resolved in next release.
