### ISSUE TITLE
name 'get_atten' is not defined

### ISSUE THREAD

**Issue by Gmgge** [zhanghang1989/PyTorch-Encoding#180]
File "/home/x/anaconda3/envs/pt/lib/python3.6/site-packages/encoding/models/__init__.py", line 16, in get_segmentation_model
    'atten': get_atten,
NameError: name 'get_atten' is not defined
I did not find the definition of this function, is it a version problem?
pytorch1.0.0 cuda 10.0 ninja python3.6

**Comment by zhanghang1989** [comment]
Sorry about this mistake. Please comment out that line. The model of atten (CVPR 2019) will be released later.

**Comment by Gmgge** [comment]
Thank you very much for your answer.My current machine is a single gpu, no debugging success. Now debugging the two gpu machines, can I use the previous version?Because the two gpu machines don't belong to me, they are also loaded with cuda9.0.

**Comment by kukby** [comment]
@zhanghang1989 Thank you for your work. Now I have the same problem. I want to know how to solve it.
mask_file: /home/kukby/.encoding/data/VOCdevkit/VOC2010/val.pth
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    trainer = Trainer(args)
  File "train.py", line 55, in __init__
    base_size=args.base_size, crop_size=args.crop_size)
  File "/home/kukby/.local/lib/python3.6/site-packages/encoding/models/__init__.py", line 16, in get_segmentation_model
    'atten': get_atten,
NameError: name 'get_atten' is not defined

**Comment by kukby** [comment]
@zhanghang1989 Thank you for your work.  I have the same problem.  Can you share what should I do?
mask_file: /home/kukby/.encoding/data/VOCdevkit/VOC2010/val.pth
Traceback (most recent call last):
File "train.py", line 175, in
trainer = Trainer(args)
File "train.py", line 55, in init
base_size=args.base_size, crop_size=args.crop_size)
File "/home/kukby/.local/lib/python3.6/site-packages/encoding/models/init.py", line 16, in get_segmentation_model
'atten': get_atten,
NameError: name 'get_atten' is not defined

**Comment by zhanghang1989** [comment]
Sorry that I don't have time to clean and test the code. I am sharing it through gist https://gist.github.com/zhanghang1989/68b94e79892d420eeabf6e25edae8133
