### ISSUE TITLE
How can I use TripletMarginLoss with DataParallelCriterion?

### ISSUE THREAD

**Issue by Yoon-jae** [zhanghang1989/PyTorch-Encoding#184]
I'd like to use triplet loss using DataParallelCriterion as follows.

``` python
model = Model()
model = DataParallelModel(model).cuda()

criterion = nn.TripletMarginLoss(margin=config.triplet_margin)
criterion = DataParallelCriterion(criterion).cuda()

a_embs = model(a_node)
p_embs = model(p_node)
n_embs = model(n_node)

loss = criterion(a_embs, p_embs, n_embs)
```
Then I got this error.
```
Traceback (most recent call last):
  File "sync_train.py", line 424, in <module>
    main()
  File "sync_train.py", line 108, in main
    train(sync_train_data, model, criterion, optimizer, epoch, config)
  File "sync_train.py", line 199, in train
    loss = criterion(a_embs, p_embs, n_embs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/myProject/parallel.py", line 140, in forward
    outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/myProject/parallel.py", line 194, in _criterion_parallel_apply
    raise output
  File "/myProject/parallel.py", line 168, in _worker
    output = module(*(input + target), **kwargs)
TypeError: add() received an invalid combination of arguments - got (tuple), but expected one of:
 * (Tensor other, Number alpha)
 * (Number other, Number alpha)
```

I already tried [this](https://github.com/zhanghang1989/PyTorch-Encoding/issues/116#issuecomment-418137219), but it doesn't work for me.

Could you help me?

**Comment by zhanghang1989** [comment]
The easiest way is combining the models into a single one, which has multiple inputs and outputs.

**Comment by Yoon-jae** [comment]
Any other suggestion? I have some reasons that couldn't change the model structure.

**Comment by zhanghang1989** [comment]
The other way will be complicated. You may manually combine the model outputs before feeding into the loss.
