### ISSUE TITLE
I get RuntimeError: Error building extension 'enclib_cpu':

### ISSUE THREAD

**Issue by Cverlpeng** [zhanghang1989/PyTorch-Encoding#189]
hi, I get this error, who can help me ? thanks!!!

Traceback (most recent call last):
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_nullmax.py", line 17, in <module>
    import encoding.utils as utils
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, dilated, parallel, utils, models, datasets
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/nn/encoding.py", line 19, in <module>
    from ..functions import scaledL2, aggregate, pairwise_cosine
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/__init__.py", line 12, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'enclib_cpu': [1/3] c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/lpeng/anaconda3/envs/laneseg/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
FAILED: roi_align_cpu.o 
c++ -MMD -MF roi_align_cpu.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/lpeng/anaconda3/envs/laneseg/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp -o roi_align_cpu.o
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In function ‘at::Tensor ROIAlignForwardCPU(const at::Tensor&, const at::Tensor&, int64_t, int64_t, double, int64_t)’:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:407:30: error: ‘struct at::Type’ has no member named ‘tensor’
   auto output = input.type().tensor({num_rois, channels, pooled_height, pooled_width});
                              ^
In file included from /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:9:0,
                 from /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:1:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:27: error: expected primary-expression before ‘>’ token
       output.data<scalar_t>());
                           ^
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:29: error: expected primary-expression before ‘)’ token
       output.data<scalar_t>());
                             ^
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:27: error: expected primary-expression before ‘>’ token
       output.data<scalar_t>());
                           ^
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:425:29: error: expected primary-expression before ‘)’ token
       output.data<scalar_t>());
                             ^
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In function ‘at::Tensor ROIAlignBackwardCPU(const at::Tensor&, const at::Tensor&, int64_t, int64_t, int64_t, int64_t, int64_t, int64_t, double, int64_t)’:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:454:37: error: ‘struct at::Type’ has no member named ‘tensor’
   auto grad_in = bottom_rois.type().tensor({b_size, channels, height, width}).zero_(); 
                                     ^
In file included from /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/ATen/ATen.h:9:0,
                 from /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:1:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:28: error: expected primary-expression before ‘>’ token
       grad_in.data<scalar_t>(),
                            ^
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:30: error: expected primary-expression before ‘)’ token
       grad_in.data<scalar_t>(),
                              ^
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp: In lambda function:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:28: error: expected primary-expression before ‘>’ token
       grad_in.data<scalar_t>(),
                            ^
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align_cpu.cpp:470:30: error: expected primary-expression before ‘)’ token
       grad_in.data<scalar_t>(),
                              ^
[2/3] c++ -MMD -MF roi_align.o.d -DTORCH_EXTENSION_NAME=enclib_cpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/THC -isystem /home/lpeng/anaconda3/envs/laneseg/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align.cpp -o roi_align.o
In file included from /home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/encoding/lib/cpu/roi_align.cpp:1:0:
/home/lpeng/anaconda3/envs/laneseg/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \
  ^
ninja: build stopped: subcommand failed.

![image](https://user-images.githubusercontent.com/46803558/55862017-31d32580-5baa-11e9-87e6-b7f729deaf82.png)
![image](https://user-images.githubusercontent.com/46803558/55862042-42839b80-5baa-11e9-930c-4eb66963254a.png)
![image](https://user-images.githubusercontent.com/46803558/55862099-5929f280-5baa-11e9-97a0-0918b6ece5f3.png)

**Comment by Gmgge** [comment]
你尝试下torch =1.0.0

**Comment by tjulyz** [comment]
Have you solved your problem? I meet the same problem.

**Comment by Dirtybluer** [comment]
same problem

**Comment by Lydia-z** [comment]
same problem

**Comment by zyongbei** [comment]
maybe it is usefull "https://zhuanlan.zhihu.com/p/53418563"

**Comment by Northzhangmingzhe** [comment]
same

**Comment by yemucong** [comment]
same

**Comment by StacyYang** [comment]
FYI PyTorch has supported SyncBN officially. The author is not maintaining this repo and has moved to MXNet

**Comment by Dirtybluer** [comment]
> FYI PyTorch has supported SyncBN officially. The author is not maintaining this repo and has moved to MXNet

Could you please provide a reference to Pytorch's official SyncBN? Thanks a lot!

**Comment by qiaoyaya2011** [comment]
I also meet this problem. i have tried many version.   No module named 'enclib_cpu' @tjulyz @zyongbei @Northzhangmingzhe @yemucong @StacyYang

**Comment by zhanghang1989** [comment]
Could you try the detailed steps here https://hangzhang.org/PyTorch-Encoding/notes/compile.html#detailed-steps

**Comment by zhanghang1989** [comment]
BTW, please use pytorch 1.4.0

**Comment by qiaoyaya2011** [comment]
> Could you try the detailed steps here https://hangzhang.org/PyTorch-Encoding/notes/compile.html#detailed-steps

Thank you for your reply，but
i have tired mang times,doesn't work. Same as all your steps and version.  I installed it for a full 2 days and still reported the error。ImportError: No module named 'enclib_cpu'  or  ImportError: No module named 'enclib_gpu'.  torch version is 1.4 and 1.0 and 1.1 ,i have all tried. and cuda version 10.0,    cudnn version 7.5。all doesn.'t work

**Comment by qiaoyaya2011** [comment]
> Could you try the detailed steps here https://hangzhang.org/PyTorch-Encoding/notes/compile.html#detailed-steps

I recalled that this step ‘ conda install pytorch torchvision cudatoolkit=10.0 -c pytorch’ is different from yours, I used it this way，first ,i add source to anaconda 'conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/', and then i execute 'conda install pytorch torchvision cudatoolkit=10.0'
do you think the source of 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/' have  some problem?

**Comment by qiaoyaya2011** [comment]
I have solved my problem .
