### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Hyakuju** [zhanghang1989/PyTorch-Encoding#199]
I got an error when i tried to run the train.py
my environment is 
CUDA: 10.1
Cudnn: 7.5
Nvidia Driver: 418.67
Pytorch: 1.1.0

and when i set nocuda to TRUE, this error doesnt occur

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    main()
  File "main.py", line 143, in main
    train(epoch)
  File "main.py", line 93, in train
    loss.backward()
  File "/home/czh/.local/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/czh/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

btw, i passed the cudnn test. i think there may be nothing wrong with the installation of the cudnn

how can i solve this problem

thanks a lot

**Comment by Hyakuju** [comment]
okay it seems that torch 1.0.1 can solve it
