### ISSUE TITLE
No module named _encoding_lib when running python setup.py install

### ISSUE THREAD

**Issue by funnyzhou** [zhanghang1989/PyTorch-Encoding#20]
Traceback (most recent call last):
  File "test/test.py", line 11, in <module>
    import encoding
  File "/home/work/Library/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    import encoding.nn
  File "/home/work/Library/PyTorch-Encoding/encoding/nn/__init__.py", line 11, in <module>
    from .encoding import *
  File "/home/work/Library/PyTorch-Encoding/encoding/nn/encoding.py", line 17, in <module>
    from .._ext import encoding_lib
  File "/home/work/Library/PyTorch-Encoding/encoding/_ext/encoding_lib/__init__.py", line 3, in <module>
    from ._encoding_lib import lib as _lib, ffi as _ffi
ImportError: No module named _encoding_lib

**Comment by zhanghang1989** [comment]
Have you compiled and installed the package?

**Comment by funnyzhou** [comment]
I've installed pytorch and used python 2.7 (on ubuntu 14.04). When compiling your package (python setup.py install), this error occurred.

**Comment by zhanghang1989** [comment]
This package only works with python3. Can you install it with python3?
