### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by 1829805046** [zhanghang1989/PyTorch-Encoding#200]
When I use EncNet to train the ADE20k Dataset, I got this bug that I can not solve:
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    trainer.training(epoch)
  File "train.py", line 110, in training
    loss = self.criterion(outputs, target)
  File "/home/czh/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/czh/anaconda3/lib/python3.6/site-packages/encoding/parallel.py", line 130, in forward
    return self.module(inputs, *targets[0], **kwargs[0])
  File "/home/czh/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/czh/anaconda3/lib/python3.6/site-packages/encoding/nn/loss.py", line 36, in forward
    pred1, se_pred, pred2, target = tuple(inputs)
ValueError: not enough values to unpack (expected 4, got 2)

(anaconda3;python3.6.8;pytorch1.0.1;cuda10;GPU:only one 2070)

**Comment by 1829805046** [comment]
When I train the model on two GPUs, this problem can be solved. 
If you only have one GPU, you can not achieve this encnet.
