### ISSUE TITLE
ImportError: No module named 'enclib_gpu'

### ISSUE THREAD

**Issue by tjulyz** [zhanghang1989/PyTorch-Encoding#207]
cuda 10.0, ubuntu 14.04, cudnn 7.1, pytorch 1.1 installed by conda, python=3.6.5.

>>> import encoding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/encoding/lib/__init__.py", line 27, in <module>
    build_directory=gpu_path, verbose=False)
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 967, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/vpa/anaconda2/envs/pyenc/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'enclib_gpu'

**Comment by OasisYang** [comment]
I met the same problem

**Comment by tjulyz** [comment]
@OasisYang  I have successfully installed this package with pytorch1.0.0 cuda10.0 ubuntu16.04/14.04 python 3.6.7. Maybe you can refer to my github for the installation.
