### ISSUE TITLE
ModuleNotFoundError: No module named 'dataloader.minc'

### ISSUE THREAD

**Issue by WONQIAN** [zhanghang1989/PyTorch-Encoding#213]
```
Traceback (most recent call last):
  File "D:/GitHub/Deep-Encoding-Pooling-Network-DEP-/train.py", line 172, in <module>
    main()
  File "D:/GitHub/Deep-Encoding-Pooling-Network-DEP-/train.py", line 45, in main
    dataset = importlib.import_module('dataloader.'+args.dataset)
  File "C:\anaconda\envs\python36\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dataloader.minc'
```

how to deal with this problem? dear zhang.

**Comment by WONQIAN** [comment]
i run this in win10
