### ISSUE TITLE
Error when import encoding

### ISSUE THREAD

**Issue by Lydia-z** [zhanghang1989/PyTorch-Encoding#219]
>>> import encoding
Traceback (most recent call last):
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 946, in _build_extension_module
    check=True)
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/__init__.py", line 27, in <module>
    build_directory=gpu_path, verbose=False)
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 814, in _jit_compile
    with_cuda=with_cuda)
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 863, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 959, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'enclib_gpu': [1/8] c++ -MMD -MF operator.o.d -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/operator.cpp -o operator.o
[2/8] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/encodingv2_kernel.cu -o encodingv2_kernel.cuda.o
FAILED: encodingv2_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/encodingv2_kernel.cu -o encodingv2_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00002006_00000000-7_encodingv2_kernel.cpp1.ii".
[3/8] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
FAILED: syncbn_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00002007_00000000-7_syncbn_kernel.cpp1.ii".
[4/8] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/encoding_kernel.cu -o encoding_kernel.cuda.o
FAILED: encoding_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/encoding_kernel.cu -o encoding_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00002003_00000000-7_encoding_kernel.cpp1.ii".
[5/8] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/roi_align_kernel.cu -o roi_align_kernel.cuda.o
FAILED: roi_align_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/roi_align_kernel.cu -o roi_align_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00002008_00000000-7_roi_align_kernel.cpp1.ii".
[6/8] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
FAILED: nms_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00002009_00000000-7_nms_kernel.cpp1.ii".
[7/8] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/activation_kernel.cu -o activation_kernel.cuda.o
FAILED: activation_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/api/include -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/TH -isystem /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/THC -isystem /usr/local/cuda/include -isystem /home/machine-k40/anaconda3/envs/encnet/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/encoding/lib/gpu/activation_kernel.cu -o activation_kernel.cuda.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/home/machine-k40/anaconda3/envs/encnet/lib/python3.6/site-packages/torch/lib/include/torch/csrc/jit/argument_spec.h(59): error: static assertion failed with "ArgumentInfo is to be a POD struct"

1 error detected in the compilation of "/tmp/tmpxft_00002005_00000000-7_activation_kernel.cpp1.ii".
ninja: build stopped: subcommand failed.

**Comment by cbrockschmidt** [comment]
Try this: https://github.com/zhanghang1989/PyTorch-Encoding/issues/161#issuecomment-450132800

**Comment by zhanghang1989** [comment]
I just update the repo recently, let me know if you still have any trouble.
