### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by sukhad-app** [zhanghang1989/PyTorch-Encoding#22]
on setup.py install, I get the following output 
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    'install': install,
  File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 336, in __init__
    _Distribution.__init__(self, attrs)
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 470, in finalize_options
    ep.load()(self, ep.name, value)
  File "/home/sukhad/PyTorch-Encoding/.eggs/cffi-1.11.2-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 188, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/sukhad/PyTorch-Encoding/.eggs/cffi-1.11.2-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/sukhad/PyTorch-Encoding/.eggs/cffi-1.11.2-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "/home/sukhad/PyTorch-Encoding/build.py", line 36, in <module>
    subprocess.check_call(build_all_cmd, env=dict(os.environ))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'encoding/make.sh']' returned non-zero exit status 2

**Comment by zhanghang1989** [comment]
Please use python3. Let me know if it works

**Comment by sukhad-app** [comment]
Thanks , it worked but now when I try to test on pre-trained model using the following command 
python main.py --dataset minc --model encodingnet --resume model/minc.pth.tar --eval

I get the following error 
No module named encoding.

**Comment by zhanghang1989** [comment]
if you install the package with python3, please execute the code with python3.

**Comment by liruilong940607** [comment]
This issue also appears in python3.4.

Using python3.5 can solve this.
