### ISSUE TITLE
RuntimeError device-side assert triggered

### ISSUE THREAD

**Issue by pribadihcr** [zhanghang1989/PyTorch-Encoding#23]
Hi @zhanghang1989,
I got the following error when run: python3 main.py --dataset minc --model deepten --batch-size 64 --lr 0.01 --epochs 60

  THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "main.py", line 171, in <module>
    main()
  File "main.py", line 157, in main
    train(epoch)
  File "main.py", line 92, in train
    loss.backward()
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by pribadihcr** [comment]
Solved. I define --nclass 23 for minc-2500 dataset.
