### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'train'

### ISSUE THREAD

**Issue by 2014ZDH** [zhanghang1989/PyTorch-Encoding#233]
Hello, I am using the statement you provided here 
Encoding/experiments/texture.html
python main.py --dataset minc --model deepten_resnet50_minc --nclass 23  --pretrained --eval
Test pre-trained model on MINC-2500
But the following error occurred:
![image](https://user-images.githubusercontent.com/38283351/68068311-449f8880-fd8e-11e9-872e-0da38019234b.png)
What should I do?

**Comment by chccgiven** [comment]
> should I do?

Hi, I got the same error, have you solved it? 
Hope for your reply.
Thank you!

**Comment by chccgiven** [comment]
> Hello, I am using the statement you provided here
> Encoding/experiments/texture.html
> python main.py --dataset minc --model deepten_resnet50_minc --nclass 23 --pretrained --eval
> Test pre-trained model on MINC-2500
> But the following error occurred:
> ![image](https://user-images.githubusercontent.com/38283351/68068311-449f8880-fd8e-11e9-872e-0da38019234b.png)
> What should I do?

Hi, I got the same error, have you solved it?
Hope for your reply.
Thank you!

**Comment by a0988731275** [comment]
```
Namespace(backbone='resnet50', batch_size=128, checkname='default', cuda=True, dataset='minc', epochs=600, eval=True, lr=0.1, lr_scheduler='cos', lr_step=40, model='deepten_resnet50_minc', momentum=0.9, nclass=23, ncodes=32, no_cuda=False, plot=False, pretrained=True, resume=None, seed=1, start_epoch=1, test_batch_size=256, weight_decay=0.0001, widen=4, workers=16)
Traceback (most recent call last):
  File "main.py", line 181, in <module>
    main()
  File "main.py", line 38, in main
    transform=transform_train, train=True, download=True)
  File "/home/pingrui/Desktop/Deepten/lib/python3.6/site-packages/encoding/datasets/__init__.py", line 39, in get_dataset
    return datasets [name.lower()] (**kwargs)
TypeError: __init__() got an unexpected keyword argument 'train'
```
hello,  i got the same error, have you all solved it?
hope for your reply. thank you ^ ^

**Comment by roseif** [comment]
I  am encoutered problems as you
