### ISSUE TITLE
import encoding in Pycharm => FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'

### ISSUE THREAD

**Issue by ipScore** [zhanghang1989/PyTorch-Encoding#260]
Environ:
```
Docker Container from https://ngc.nvidia.com/catalog/containers/nvidia:pytorch/tags
docker pull nvcr.io/nvidia/pytorch:19.12-py3
Ubuntu 16.04
Python == 3.6.9
PyTorch == 1.4.0
ninja == 1.9.0
torch-encoding == 1.2.0b20200421
CUDA Version: 10.1
```

When `import encoding` within comand line, everything is OK:

![image](https://user-images.githubusercontent.com/30183023/79986082-16e60180-84de-11ea-9dec-4deeec948c04.png)

However, when import encoding in Pycharm, it raises a error as the following:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 929, in verify_ninja_availability
    subprocess.check_call('ninja --version'.split(), stdout=devnull)
  File "/opt/conda/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/conda/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/conda/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ninja': 'ninja'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/pyroom/jiangjie/TorchEncoding/segmodel/pre_train_model/seg_model_eval.py", line 1, in <module>
    import encoding
  File "/opt/conda/lib/python3.6/site-packages/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/opt/conda/lib/python3.6/site-packages/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/opt/conda/lib/python3.6/site-packages/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/opt/conda/lib/python3.6/site-packages/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/opt/conda/lib/python3.6/site-packages/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/opt/conda/lib/python3.6/site-packages/encoding/lib/__init__.py", line 16, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 680, in load
    is_python_module)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 866, in _jit_compile
    with_cuda=with_cuda)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 889, in _write_ninja_file_and_build
    verify_ninja_availability()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 931, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions

Process finished with exit code 1
```

**Comment by ipScore** [comment]
Following the instuctions from `https://ninja-build.org/` and `https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages`:

for example,` Debian/Ubuntu: apt-get install ninja-build`

then everything will be OK even in `Pycharm`
