### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'log_softmax'

### ISSUE THREAD

**Issue by blackmagicianZ** [zhanghang1989/PyTorch-Encoding#274]
Using poly LR scheduler with warm-up epochs of 0!
Starting Epoch: 0
Total Epoches: 50
  0%|                                                                                                                                                                                | 0/364 [00:00<?, ?it/s]
=>Epoch 0, learning rate = 0.0001,                     previous best = 0.0000
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    trainer.training(epoch)
  File "train.py", line 203, in training
    loss = self.criterion(outputs, target)
  File "/opt/conda/envs/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/python3/lib/python3.6/site-packages/encoding/parallel.py", line 130, in forward
    return self.module(inputs, *targets[0], **kwargs[0])
  File "/opt/conda/envs/python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/envs/python3/lib/python3.6/site-packages/encoding/nn/loss.py", line 68, in forward
    return super(SegmentationLosses, self).forward(*inputs)
  File "/opt/conda/envs/python3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/opt/conda/envs/python3/lib/python3.6/site-packages/torch/nn/functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/opt/conda/envs/python3/lib/python3.6/site-packages/torch/nn/functional.py", line 1317, in log_softmax
    ret = input.log_softmax(dim)
AttributeError: 'tuple' object has no attribute 'log_softmax'

run scripts: python train.py --dataset pascal_voc --batch-size 8 --model deeplab

**Comment by zhanghang1989** [comment]
Which pytorch version are you using?

**Comment by zhanghang1989** [comment]
How many gpu do you have?

**Comment by blackmagicianZ** [comment]
> Which pytorch version are you using?

1.4

**Comment by blackmagicianZ** [comment]
> How many gpu do you have?

only one

**Comment by blackmagicianZ** [comment]
> How many gpu do you have?

Solved by 2 gpus, thank for your reply.
