### ISSUE TITLE
no longer main.py in deepTEN encoding

### ISSUE THREAD

**Issue by A201124253** [zhanghang1989/PyTorch-Encoding#285]
hello Zhang,
I want to "Test pre-trained model on MINC-2500" using deepTEN, but there is no longer "main.py" in this folder.
How to test the model on MINC-2500 now?
zhijie li

**Comment by A201124253** [comment]
> Could you try `verify.py`?
I have found  `verify.py` in ~/PyTorch-Encoding/experiments/recognition/verify.py and tryed
"python verify.py --dataset minc --model deepten_resnet50_minc --nclass 23  --pretrained --eval"
but 
(base) lzj@ros:~/PyTorch-Encoding/experiments/recognition$ python verify.py --dataset minc --model deepten_resnet50_minc --nclass 23  --pretrained --eval
usage: verify.py [-h] [--dataset DATASET] [--base-size BASE_SIZE]
                 [--crop-size CROP_SIZE] [--model MODEL] [--rectify]
                 [--rectify-avg] [--batch-size N] [--workers N] [--no-cuda]
                 [--seed S] [--resume RESUME] [--verify VERIFY]
                 [--export EXPORT]
verify.py: error: unrecognized arguments: --nclass 23 --pretrained --eval

I can not set this three arguments.

**Comment by A201124253** [comment]
then I ran "python verify.py --dataset minc --model deepten_resnet50_minc"
it works but I must delete the argument "train=False, download=True" in "verify.py", because 

(base) lzj@ros:~/PyTorch-Encoding/experiments/recognition$ python verify.py --dataset minc --model deepten_resnet50_minc 
Namespace(base_size=None, batch_size=128, crop_size=224, cuda=True, dataset='minc', export=None, model='deepten_resnet50_minc', no_cuda=False, rectify=False, rectify_avg=False, resume=None, seed=1, verify=None, workers=32)
Traceback (most recent call last):
  File "verify.py", line 132, in <module>
    main()
  File "verify.py", line 72, in main
    transform=transform_val, train=False, download=True)
  File "/home/lzj/anaconda3/lib/python3.7/site-packages/torch_encoding-1.2.1b20200603-py3.7.egg/encoding/datasets/__init__.py", line 39, in get_dataset
    return datasets[name.lower()](**kwargs)
TypeError: __init__() got an unexpected keyword argument 'train'

**Comment by zhanghang1989** [comment]
Thanks for the feedback. The training code on MINC is broken. But I think you should be able to fix it easily.

**Comment by A201124253** [comment]
> Thanks for the feedback. The training code on MINC is broken. But I think you should be able to fix it easily.

Thank you for your reply.
