### ISSUE TITLE
python setup.py install  PROBLEM

### ISSUE THREAD

**Issue by BinbinBian** [zhanghang1989/PyTorch-Encoding#29]
Hi, 
I failed to install from this source .Why is it?
`
/usr/include/c++/4.8/cmath(406): error: expected a ";"

/usr/include/c++/4.8/cmath(443): error: inline specifier allowed on function declarations only

/usr/include/c++/4.8/cmath(443): error: variable "std::constexpr" has already been defined

/usr/include/c++/4.8/cmath(443): error: expected a ";"

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00002889_00000000-17_thc_encoding.compute_61.cpp1.ii".
Compilation terminated.
CMake Error at ENCODING_generated_thc_encoding.cu.o.cmake:264 (message):
  Error generating file
  /home/bbbian/local/PyTorch-Encoding/encoding/lib/CMakeFiles/ENCODING.dir/kernel/./ENCODING_generated_thc_encoding.cu.o

make[2]: *** [CMakeFiles/ENCODING.dir/kernel/./ENCODING_generated_thc_encoding.cu.o] Error 1
make[1]: *** [CMakeFiles/ENCODING.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    'install': install,
  File "/home/bbbian/local/anaconda3/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/bbbian/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 318, in __init__
  File "/home/bbbian/local/anaconda3/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/home/bbbian/local/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/dist.py", line 375, in finalize_options
  File "/home/bbbian/local/anaconda3/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 187, in cffi_modules
    add_cffi_module(dist, cffi_module)
  File "/home/bbbian/local/anaconda3/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
    execfile(build_file_name, mod_vars)
  File "/home/bbbian/local/anaconda3/lib/python3.6/site-packages/cffi/setuptools_ext.py", line 25, in execfile
    exec(code, glob, glob)
  File "/home/bbbian/local/PyTorch-Encoding/build.py", line 37, in <module>
    subprocess.check_call(build_all_cmd, env=dict(os.environ))
  File "/home/bbbian/local/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'encoding/make.sh']' returned non-zero exit status 2.
`

**Comment by zhanghang1989** [comment]
Have you successfully install PyTorch from source?

**Comment by BinbinBian** [comment]
@zhanghang1989  I intall Pytorch use this command : pip install http://download.pytorch.org/whl/cu80/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl 
I tried on different server platform,all failed.

**Comment by lxtGH** [comment]
Hi! @zhanghang1989 I have **installed** **pytorch** from the source. but I still got this error
torch version 0.4.0a0+063946d
running install_egg_info
running egg_info
creating encoding.egg-info
writing encoding.egg-info/PKG-INFO
writing dependency_links to encoding.egg-info/dependency_links.txt
writing requirements to encoding.egg-info/requires.txt
writing top-level names to encoding.egg-info/top_level.txt
writing manifest file 'encoding.egg-info/SOURCES.txt'
reading manifest file 'encoding.egg-info/SOURCES.txt'
writing manifest file 'encoding.egg-info/SOURCES.txt'
Copying encoding.egg-info to /home/lxt/anaconda3/lib/python3.6/site-packages/encoding-0.2.0+d40adbc-py3.6.egg-info
running install_scripts
Traceback (most recent call last):
  File "test/test.py", line 74, in <module>
    test_scaledL2()
  File "test/test.py", line 42, in test_scaledL2
    test = gradcheck(encoding.functions.scaledL2, input, eps=1e-6, atol=1e-4)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/torch/autograd/gradcheck.py", line 162, in gradcheck
    output = _differentiable_outputs(func(*inputs))
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 135, in scaledL2
    return _scaledL2.apply(X, C, S)
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 95, in forward
    encoding_lib.Encoding_Double_scaledl2_forward(SL, X, C, S)
AttributeError: module 'encoding._ext.encoding_lib' has no attribute 'Encoding_Double_scaledl2_forward'
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    'install': install,
  File "/home/lxt/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/lxt/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/lxt/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/lxt/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 26, in run
    subprocess.check_call("python test/test.py".split())
  File "/home/lxt/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'test/test.py']' returned non-zero exit status 1

**Comment by lxtGH** [comment]
Ok, I fix it by doing git pull and clean.sh , then re install
