### ISSUE TITLE
Error building extension 'enclib_gpu'

### ISSUE THREAD

**Issue by qiulesun** [zhanghang1989/PyTorch-Encoding#297]
**OS: ubuntu 16.04
torch: 1.4.0+cu100
cuda: 10.0.130
python: 3.6.10**

**When I install torch-encoding using pip install torch-encoding --pre, I got the following info without reporting any errors:**

(pytorch_140_env) root@hh-ubuntu:/media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding# pip install torch-encoding --pre
Requirement already satisfied: torch-encoding in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch_encoding-1.2.2b20200713-py3.6.egg (1.2.2b20200713)
Requirement already satisfied: numpy in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages (from torch-encoding) (1.19.0)
Requirement already satisfied: tqdm in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/tqdm-4.47.0-py3.6.egg (from torch-encoding) (4.47.0)
Requirement already satisfied: nose in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/nose-1.3.7-py3.6.egg (from torch-encoding) (1.3.7)
Requirement already satisfied: portalocker in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/portalocker-1.7.0-py3.6.egg (from torch-encoding) (1.7.0)
Requirement already satisfied: torch>=1.4.0 in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages (from torch-encoding) (1.4.0+cu100)
Requirement already satisfied: torchvision>=0.5.0 in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages (from torch-encoding) (0.5.0+cu100)
Requirement already satisfied: Pillow in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages (from torch-encoding) (7.2.0)
Requirement already satisfied: scipy in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/scipy-1.5.1-py3.6-linux-x86_64.egg (from torch-encoding) (1.5.1)
Requirement already satisfied: requests in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/requests-2.24.0-py3.6.egg (from torch-encoding) (2.24.0)
Requirement already satisfied: six in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages (from torchvision>=0.5.0->torch-encoding) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages (from requests->torch-encoding) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/chardet-3.0.4-py3.6.egg (from requests->torch-encoding) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/idna-2.10-py3.6.egg (from requests->torch-encoding) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/urllib3-1.25.9-py3.6.egg (from requests->torch-encoding) (1.25.9)

**Howerver, when I import encoding, I got the next error. How can I fix it ?**

(pytorch_140_env) root@hh-ubuntu:/media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding# python 
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import encoding
Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1066, in _build_extension_module
    check=True)
  File "/usr/anaconda3/envs/pytorch_140_env/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/functions/encoding.py", line 14, in <module>
    from .. import lib
  File "/media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/__init__.py", line 29, in <module>
    build_directory=gpu_path, verbose=False)
  File "/usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 680, in load
    is_python_module)
  File "/usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 866, in _jit_compile
    with_cuda=with_cuda)
  File "/usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 919, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1079, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'enclib_gpu': [1/8] :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/encoding_kernel.cu -o encoding_kernel.cuda.o
FAILED: encoding_kernel.cuda.o 
:/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/encoding_kernel.cu -o encoding_kernel.cuda.o
/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
[2/8] :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/activation_kernel.cu -o activation_kernel.cuda.o
FAILED: activation_kernel.cuda.o 
:/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/activation_kernel.cu -o activation_kernel.cuda.o
/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
[3/8] :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
FAILED: syncbn_kernel.cuda.o 
:/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/syncbn_kernel.cu -o syncbn_kernel.cuda.o
/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
[4/8] :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/roi_align_kernel.cu -o roi_align_kernel.cuda.o
FAILED: roi_align_kernel.cuda.o 
:/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/roi_align_kernel.cu -o roi_align_kernel.cuda.o
/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
[5/8] :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/rectify_cuda.cu -o rectify_cuda.cuda.o
FAILED: rectify_cuda.cuda.o 
:/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/rectify_cuda.cu -o rectify_cuda.cuda.o
/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
[6/8] :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
FAILED: nms_kernel.cuda.o 
:/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/nms_kernel.cu -o nms_kernel.cuda.o
/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
[7/8] :/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/lib_ssd.cu -o lib_ssd.cuda.o
FAILED: lib_ssd.cuda.o 
:/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=enclib_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/TH -isystem /usr/anaconda3/envs/pytorch_140_env/lib/python3.6/site-packages/torch/include/THC -isystem :/usr/local/cuda/include -isystem /usr/anaconda3/envs/pytorch_140_env/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' --expt-extended-lambda -std=c++11 -c /media/hh/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/new_version_torch_encoding/PyTorch-Encoding/encoding/lib/gpu/lib_ssd.cu -o lib_ssd.cuda.o
/bin/sh: 1: :/usr/local/cuda/bin/nvcc: not found
ninja: build stopped: subcommand failed.

**Comment by zhanghang1989** [comment]
Please install ninja as in the instructions:
https://hangzhang.org/PyTorch-Encoding/notes/compile.html#detailed-steps

**Comment by qiulesun** [comment]
@zhanghang1989 I install ninja, torch-encoding from pip and source fully following the instructions:
https://hangzhang.org/PyTorch-Encoding/notes/compile.html#detailed-steps. 
Please note thate there are no issues during install torch-encoding. However, when I import encoding, above errors happen.

**Comment by qiaoyaya2011** [comment]
@qiulesun  how do you deal with it?

**Comment by qiaoyaya2011** [comment]
I have solved my problem

**Comment by aimshirley** [comment]
> I have solved my problem. Thanks for your reply.

How did you solve the problem
