### ISSUE TITLE
A RuntimeError about deepcopy occur at runing train_dist.py

### ISSUE THREAD

**Issue by Jie2World** [zhanghang1989/PyTorch-Encoding#299]
Pytorch vision: 1.4.0; 
torchvision:0.5.0;
cuda vison:10.2
I run the train_dist.py follow the tutorial of https://hangzhang.org//PyTorch-Encoding/tutorials/texture.html.
But I meet a RuntimeError of deepcopy. 
" **RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment.** "

The detail error report:
`Using step LR scheduler with warm-up epochs of 0!

=>Epoch 0, learning rate = 0.0040,                     previous best = 0.0000
Traceback (most recent call last):
  File "train_dist.py", line 371, in <module>
    main()
  File "train_dist.py", line 119, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ubuntu/Documents/MLProjects/hwj/PyTorch-Encoding/experiments/recognition/train_dist.py", line 353, in main_worker
    train(epoch)
  File "/home/ubuntu/Documents/MLProjects/hwj/PyTorch-Encoding/experiments/recognition/train_dist.py", line 280, in train
    output = model(data)
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/site-packages/torch_encoding-1.2.2b20200717-py3.6.egg/encoding/models/deepten.py", line 62, in forward
    temp_x = copy.deepcopy(x)
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/home/ubuntu/anaconda3/envs/deepten/lib/python3.6/site-packages/torch/tensor.py", line 44, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
**RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment**`

**Comment by Jie2World** [comment]
I also report that the '--lr-step 60' is valid at "Train Your Own Model" of  'https://hangzhang.org//PyTorch-Encoding/tutorials/texture.html'.
