### ISSUE TITLE
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

### ISSUE THREAD

**Issue by ygjwd12345** [zhanghang1989/PyTorch-Encoding#313]
as title

**Comment by zhanghang1989** [comment]
Could you try using the newest version?
```bash
pip install git+https://github.com/zhanghang1989/PyTorch-Encoding
```

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error.

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error. Your work contributes to semantic segmentation. Could you fix it as soon as possible?
The error is as follows:
=>Epoch 0, learning rate = 0.0004,                     previous best = 0.0000
  0%|          | 0/832 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 271, in <module>
    trainer.training(epoch)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 202, in training
    outputs = self.model(image)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/base.py", line 90, in base_forward
    x = self.pretrained.conv1(x)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/nn/syncbn.py", line 202, in forward
    self.activation, self.slope).view(input_shape)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/functions/syncbn.py", line 67, in forward
    _ex, _exs = gpu.expectation_forward(x)
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error. Your work contributes to semantic segmentation. Could you fix it as soon as possible?
The error is as follows:
=>Epoch 0, learning rate = 0.0004,                     previous best = 0.0000
  0%|          | 0/832 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 271, in <module>
    trainer.training(epoch)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 202, in training
    outputs = self.model(image)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/base.py", line 90, in base_forward
    x = self.pretrained.conv1(x)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/nn/syncbn.py", line 202, in forward
    self.activation, self.slope).view(input_shape)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/functions/syncbn.py", line 67, in forward
    _ex, _exs = gpu.expectation_forward(x)
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error. Your work contributes to semantic segmentation. Could you fix it as soon as possible?
The error is as follows:
=>Epoch 0, learning rate = 0.0004,                     previous best = 0.0000
  0%|          | 0/832 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 271, in <module>
    trainer.training(epoch)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 202, in training
    outputs = self.model(image)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/base.py", line 90, in base_forward
    x = self.pretrained.conv1(x)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/nn/syncbn.py", line 202, in forward
    self.activation, self.slope).view(input_shape)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/functions/syncbn.py", line 67, in forward
    _ex, _exs = gpu.expectation_forward(x)
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error. Your work contributes to semantic segmentation. Could you fix it as soon as possible?
The error is as follows:
=>Epoch 0, learning rate = 0.0004,                     previous best = 0.0000
  0%|          | 0/832 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 271, in <module>
    trainer.training(epoch)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 202, in training
    outputs = self.model(image)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/base.py", line 90, in base_forward
    x = self.pretrained.conv1(x)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/nn/syncbn.py", line 202, in forward
    self.activation, self.slope).view(input_shape)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/functions/syncbn.py", line 67, in forward
    _ex, _exs = gpu.expectation_forward(x)
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error. Your work contributes to semantic segmentation. Could you fix it as soon as possible?
The error is as follows:
=>Epoch 0, learning rate = 0.0004,                     previous best = 0.0000
  0%|          | 0/832 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 271, in <module>
    trainer.training(epoch)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 202, in training
    outputs = self.model(image)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/base.py", line 90, in base_forward
    x = self.pretrained.conv1(x)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/nn/syncbn.py", line 202, in forward
    self.activation, self.slope).view(input_shape)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/functions/syncbn.py", line 67, in forward
    _ex, _exs = gpu.expectation_forward(x)
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error. Your work contributes to semantic segmentation. Could you fix it as soon as possible?
The error is as follows:
=>Epoch 0, learning rate = 0.0004,                     previous best = 0.0000
  0%|          | 0/832 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 271, in <module>
    trainer.training(epoch)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 202, in training
    outputs = self.model(image)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/base.py", line 90, in base_forward
    x = self.pretrained.conv1(x)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/nn/syncbn.py", line 202, in forward
    self.activation, self.slope).view(input_shape)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/functions/syncbn.py", line 67, in forward
    _ex, _exs = gpu.expectation_forward(x)
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error. Your work contributes to semantic segmentation. Could you fix it as soon as possible?
The error is as follows:
=>Epoch 0, learning rate = 0.0004,                     previous best = 0.0000
  0%|          | 0/832 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 271, in <module>
    trainer.training(epoch)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 202, in training
    outputs = self.model(image)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/base.py", line 90, in base_forward
    x = self.pretrained.conv1(x)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/nn/syncbn.py", line 202, in forward
    self.activation, self.slope).view(input_shape)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/functions/syncbn.py", line 67, in forward
    _ex, _exs = gpu.expectation_forward(x)
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

**Comment by qiulesun** [comment]
@zhanghang1989 I used the newest version and met the same error. Your work contributes to semantic segmentation. Could you fix it as soon as possible?
The error is as follows:
=>Epoch 0, learning rate = 0.0004,                     previous best = 0.0000
  0%|          | 0/832 [00:17<?, ?it/s]
Traceback (most recent call last):
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 271, in <module>
    trainer.training(epoch)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/experiments/segmentation/train.py", line 202, in training
    outputs = self.model(image)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/encnet.py", line 33, in forward
    features = self.base_forward(x)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/models/sseg/base.py", line 90, in base_forward
    x = self.pretrained.conv1(x)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/anaconda3/envs/pytorch160_cuda101/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/nn/syncbn.py", line 202, in forward
    self.activation, self.slope).view(input_shape)
  File "/media/b501/0bfd0eaf-cf46-48b3-915a-aa317b67d9ec/sql/pytorch-project/pytorch160_cuda101/PyTorch-Encoding/encoding/functions/syncbn.py", line 67, in forward
    _ex, _exs = gpu.expectation_forward(x)
AttributeError: module 'encoding.lib.gpu' has no attribute 'expectation_forward'

**Comment by zhanghang1989** [comment]
The error still shows the error in previous version. `enclib` is already deprecated. 

First uninstall the previous version (run multiple times if necessary):
```
pip uninstall -y torch-encoding
```

Then install the newest version:
```
pip install git+https://github.com/zhanghang1989/PyTorch-Encoding
```

**Comment by ygjwd12345** [comment]
@zhanghang1989 Hi, zhang. I follow your guide but I get the new error.

ImportError: /data/gyang/PGA-net/PyTorch-Encoding/experiments/segmentation/encoding/lib/cpu/enclib_cpu.so: undefined symbol: _Z16CONV_RECTIFY_CPURN2at6TensorERKS0_N3c108ArrayRefIlEES6_S6_S6_b

**Comment by zhanghang1989** [comment]
Are you using the latest code?
