### ISSUE TITLE
Exception: process 0 terminated with signal SIGKILL`

### ISSUE THREAD

**Issue by dylanqyuan** [zhanghang1989/PyTorch-Encoding#324]
Hi,

dependency: 
pytorch 1.4.0, 
 CUDA 10.2 
Pytorch_encoding master branch

the following code is run on single GPU( GeForce RTX 2080, 8GB)：
`
CUDA_VISIBLE_DEVICES=0 python train_dist.py --dataset PContext --model EncNet --aux --se-loss
`

the following issue happened:

`Using poly LR scheduler with warm-up epochs of 0!
Starting Epoch: 0
Total Epoches: 80
Traceback (most recent call last):
  File "train_dist.py", line 319, in <module>
    main()
  File "train_dist.py", line 148, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/qyuan/anaconda3/envs/pytorch_encoding_interpreter/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/qyuan/anaconda3/envs/pytorch_encoding_interpreter/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGKILL`

I have read all the issues related to it, but the issue is still there,could you please give me some suggestions? thanks for your time!

**Comment by zhanghang1989** [comment]
That looks like a pytorch issue. I haven't seen this before.
