### ISSUE TITLE
encoding包安装成功后，引用报错

### ISSUE THREAD

**Issue by LEGION-LC037** [zhanghang1989/PyTorch-Encoding#358]
Using /home/user/anaconda3/lib/python3.7/site-packages
Finished processing dependencies for torch-encoding==1.2.2b20201225
您好，我在安装torch-encoding成功之后，import encoding的时候报错：

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/user/PyTorch-Encoding/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/user/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/user/PyTorch-Encoding/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/user/PyTorch-Encoding/encoding/functions/encoding.py", line 15, in <module>
    from encoding import cpu
ImportError: cannot import name 'cpu' from 'encoding' (/home/user/PyTorch-Encoding/encoding/__init__.py)

卸载重装之后还是这样报错，请问该如何解决？

**Comment by LEGION-LC037** [comment]
我的各种版本是这样的：
gcc7.3.0     python3.7.6     pytorch1.4.0    torchvision0.5.0

**Comment by zhanghang1989** [comment]
看起来好像是有多个 torch-encoding 的版本在本地，可以多run几次 `pip uninstall -y torch-encoding`
然后再重装试试 `pip install git+https://github.com/zhanghang1989/PyTorch-Encoding/`

**Comment by yjt9299** [comment]
> 看起来好像是有多个 torch-encoding 的版本在本地，可以多run几次 `pip uninstall -y torch-encoding`
> 然后再重装试试 `pip install git+https://github.com/zhanghang1989/PyTorch-Encoding/`

i meet this error too...
but i try pip uninstall -y torch-encoding   but still can not import cpu....

`(encnet) yuejiutao@lm04:~/Code/PyTorch-Encoding$ pip install git+https://github.com/zhanghang1989/PyTorch-Encoding/
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/zhanghang1989/PyTorch-Encoding/
  Cloning https://github.com/zhanghang1989/PyTorch-Encoding/ to /tmp/pip-req-build-p_d6cshw
Requirement already satisfied: numpy in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (1.15.1)
Requirement already satisfied: tqdm in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (4.26.0)
Requirement already satisfied: nose in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (1.3.7)
Requirement already satisfied: portalocker in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (2.0.0)
Requirement already satisfied: torch>=1.4.0 in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (1.6.0+cu101)
Requirement already satisfied: torchvision>=0.5.0 in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (0.7.0+cu101)
Requirement already satisfied: Pillow in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (6.1.0)
Requirement already satisfied: scipy in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (1.3.1)
Requirement already satisfied: requests in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch-encoding==1.2.2b20210121) (2.25.0)
Requirement already satisfied: future in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from torch>=1.4.0->torch-encoding==1.2.2b20210121) (0.17.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from requests->torch-encoding==1.2.2b20210121) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from requests->torch-encoding==1.2.2b20210121) (2018.8.24)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from requests->torch-encoding==1.2.2b20210121) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/yuejiutao/anaconda3/envs/encnet/lib/python3.7/site-packages (from requests->torch-encoding==1.2.2b20210121) (2.7)
Building wheels for collected packages: torch-encoding
  Building wheel for torch-encoding (setup.py) ... done
  Created wheel for torch-encoding: filename=torch_encoding-1.2.2b20210121-cp37-cp37m-linux_x86_64.whl size=6359741 sha256=97e1d6060e60338fb975aaec11325e14986565294dc35387c834a4c6b18b56c1
  Stored in directory: /tmp/pip-ephem-wheel-cache-v5dqid75/wheels/d4/83/00/5a9524a23f206528125bf76110b7304681afa76adbba084b5c
Successfully built torch-encoding
Installing collected packages: torch-encoding
Successfully installed torch-encoding-1.2.2b20210121`

**Comment by yjt9299** [comment]
> Using /home/user/anaconda3/lib/python3.7/site-packages
> Finished processing dependencies for torch-encoding==1.2.2b20201225
> 您好，我在安装torch-encoding成功之后，import encoding的时候报错：
> 
> Traceback (most recent call last):
> File "", line 1, in
> File "/home/user/PyTorch-Encoding/encoding/**init**.py", line 13, in
> from . import nn, functions, parallel, utils, models, datasets, transforms
> File "/home/user/PyTorch-Encoding/encoding/nn/**init**.py", line 12, in
> from .encoding import *
> File "/home/user/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in
> from ..functions import scaled_l2, aggregate, pairwise_cosine
> File "/home/user/PyTorch-Encoding/encoding/functions/**init**.py", line 2, in
> from .encoding import *
> File "/home/user/PyTorch-Encoding/encoding/functions/encoding.py", line 15, in
> from encoding import cpu
> ImportError: cannot import name 'cpu' from 'encoding' (/home/user/PyTorch-Encoding/encoding/**init**.py)
> 
> 卸载重装之后还是这样报错，请问该如何解决？

请问你这个问题解决了吗。。。

**Comment by yjt9299** [comment]
i got it

**Comment by zhanghang1989** [comment]
> i got it

如果问题解决了，可以分享一下经验。谢谢！

**Comment by yjt9299** [comment]
> > i got it
> 
> 如果问题解决了，可以分享一下经验。谢谢！

可能有两个原因：
pytorch版本的问题
有多个本地的encoding

**Comment by LEGION-LC037** [comment]
> > > i got it
> > 
> > 
> > 如果问题解决了，可以分享一下经验。谢谢！
> 
> 可能有两个原因：
> pytorch 版本的问题
> 有多个本地的 encoding

请问你用的pytorch是哪一个版本的？

**Comment by yjt9299** [comment]
> > > > i got it
> > > 
> > > 
> > > 如果问题解决了，可以分享一下经验。谢谢！
> > 
> > 
> > 可能有两个原因：
> > pytorch 版本的问题
> > 有多个本地的 encoding
> 
> 请问你用的pytorch是哪一个版本的？

1.4.0 好像  你康康是不是你本地有多个encoding  下载的时候采用其中一种方法就可以了

**Comment by hadwinn** [comment]
请问大佬能给个联系方式吗？请教一下。

**Comment by szy4017** [comment]
> > > > i got it
> > > 
> > > 
> > > 如果问题解决了，可以分享一下经验。谢谢！
> > 
> > 
> > 可能有两个原因：
> > pytorch 版本的问题
> > 有多个本地的 encoding
> 
> 请问你用的pytorch是哪一个版本的？

Traceback (most recent call last):
  File "scripts/prepare_pascal.py", line 6, in <module>
    from encoding.utils import download, mkdir
  File "/home/szy/PyTorch-Encoding/encoding/__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "/home/szy/PyTorch-Encoding/encoding/nn/__init__.py", line 12, in <module>
    from .encoding import *
  File "/home/szy/PyTorch-Encoding/encoding/nn/encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "/home/szy/PyTorch-Encoding/encoding/functions/__init__.py", line 2, in <module>
    from .encoding import *
  File "/home/szy/PyTorch-Encoding/encoding/functions/encoding.py", line 15, in <module>
    from encoding import cpu
ImportError: cannot import name 'cpu'

请问如何解决cpu无法引入的问题？

**Comment by zhanghang1989** [comment]
试一下：
```bash
cd scripts/
python prepare_pascal.py
```
可能是把当前路径下的 encoding 文件夹 import 了

**Comment by stu-yzZ** [comment]
> 我解决了这个问题，方法是：首先，把本地的Pytorch-Encoding文件夹都删除干净，并且使用pip uninstall torch-encoding。然后，下载github上最新的包到本地后，使用pip install ~/Downloads/PyTorch-Encoding安装就能够成功import encoding了。

hello  你好 请问下 你方便把你的环境配置发一下吗 我需要使用了你的方法还是不能成功
