### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by twister1606** [zhanghang1989/PyTorch-Encoding#362]
Traceback (most recent call last):
  File "eval.py", line 185, in <module>
    main()
  File "eval.py", line 86, in main
    model = neurvps.models.VanishingNet(
  File "C:\Users\Dimple\neurvps\neurvps\models\vanishing_net.py", line 23, in __init__
    self.anet = ApolloniusNet(output_stride, upsample_scale)
  File "C:\Users\Dimple\neurvps\neurvps\models\vanishing_net.py", line 90, in __init__
    self.conv00 = ConicConv(32, 32)
  File "C:\Users\Dimple\neurvps\neurvps\models\conic.py", line 12, in __init__
    self.deform_conv = DeformConv(
  File "C:\Users\Dimple\neurvps\neurvps\models\deformable.py", line 132, in __init__
    DCN = load_cpp_ext("DCN")
  File "C:\Users\Dimple\neurvps\neurvps\models\deformable.py", line 24, in load_cpp_ext
    ext = load(
  File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 986, in load
    return _jit_compile(
  File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1193, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1285, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1679, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1790, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args, output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Got this error while working on this project: https://github.com/zhou13/neurvps
Please help us resolve it ASAP

**Comment by zhanghang1989** [comment]
The project you mentioned is other people's work. That code is out-of-date.
