### ISSUE TITLE
How can i train on top of  research papers pre trained models

### ISSUE THREAD

**Issue by ravitejarj** [zhanghang1989/PyTorch-Encoding#370]
How to train with encnet_resnet101_ade
python train_dist.py --dataset ade20k  --model encnet --backbone encnet_resnet101s_ade --epoch 250
but not working
i got value error which list down the names of pre trained models

**Comment by zhanghang1989** [comment]
Could you add the error message to this issue? Thanks

**Comment by zhanghang1989** [comment]
Maybe your package is out-of-date. Try reinstall the newest version.

**Comment by ravitejarj** [comment]
Iam using 
Ubuntu 18.04
32GB RAM
12GB GPU
CUDA 10.1
Pytorch 1.4.0
Latest Pytorch Encoding Github Code

My commnad is:
 python train_dist.py --dataset ade20k --model encnet --backbone  get_encnet_resnet50_ade --epoch 250
Error is:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/hbbg/HBXL/PyTorch-Encoding/experiments/segmentation/train_dist.py", line 190, in main_worker
    **model_kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/__init__.py", line 20, in get_segmentation_model
    return models[name.lower()](**kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/encnet.py", line 140, in get_encnet
    model = EncNet(datasets[dataset.lower()].NUM_CLASS, backbone=backbone, root=root, **kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/encnet.py", line 24, in __init__
    norm_layer=norm_layer, **kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/base.py", line 71, in __init__
    *args, **kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/base.py", line 50, in get_backbone
    raise ValueError('%s\n\t%s' % (str(name), '\n\t'.join(sorted(models.keys()))))
ValueError: get_encnet_resnet50_ade
	resnest101
	resnest200
	resnest269
	resnest50
	resnet101
	resnet101s
	resnet152
	resnet152s
	resnet50
	resnet50d
	resnet50s
	resnext101_32x8d
	resnext50_32x4d
	wideresnet38
	wideresnet50
	xception65

**Comment by ravitejarj** [comment]
I manually downloaded encnet_resnet101s_ade from model_store.py(using url)
copied to .encoding/models

And used python train_dist.py --dataset ade20k --model encnet --backbone encnet_resnet101s_ade --epoch 250
I got same above error, which is 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/hbbg/HBXL/PyTorch-Encoding/experiments/segmentation/train_dist.py", line 190, in main_worker
    **model_kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/__init__.py", line 20, in get_segmentation_model
    return models[name.lower()](**kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/encnet.py", line 140, in get_encnet
    model = EncNet(datasets[dataset.lower()].NUM_CLASS, backbone=backbone, root=root, **kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/encnet.py", line 24, in __init__
    norm_layer=norm_layer, **kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/base.py", line 71, in __init__
    *args, **kwargs)
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/encoding/models/sseg/base.py", line 50, in get_backbone
    raise ValueError('%s\n\t%s' % (str(name), '\n\t'.join(sorted(models.keys()))))
ValueError: encnet_resnet50_ade
	resnest101
	resnest200
	resnest269
	resnest50
	resnet101
	resnet101s
	resnet152
	resnet152s
	resnet50
	resnet50d
	resnet50s
	resnext101_32x8d
	resnext50_32x4d
	wideresnet38
	wideresnet50
	xception65

**Comment by zhanghang1989** [comment]
From the error message, the backbone name seems wrong. Please use the command `--backbone resnet50s`.

**Comment by ravitejarj** [comment]
I would like train on research papers models
(you mentioned in research paper encnet model with resnest101 on ade20k images, i would like to use this model for training)
is that possible

**Comment by ravitejarj** [comment]
ok i got it
how can i use research papers pretrained model (encnet resnest101 trained on ade20k dataset)
for my custom dataset training
i tried resume operation 
python train_epoch.py --model encnet --backbone resnest101 --epochs 10 --resume models/encnet_resnet101s_ade-3f54fa3b.pth

Traceback (most recent call last):
  File "train_epoch.py", line 339, in <module>
    main()
  File "train_epoch.py", line 143, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/hbbg/miniconda3/envs/seg-pe/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/hbbg/HBXL/PyTorch-Encoding/experiments/code/train_epoch.py", line 215, in main_worker
    args.start_epoch = checkpoint['epoch']
KeyError: 'epoch'

**Comment by zhanghang1989** [comment]
That file only contains the model parameters.
You may 1). only load the model params and comment out the other code 
2). or you can pretrain your own base models.

**Comment by ravitejarj** [comment]
Thank you
