### ISSUE TITLE
Failed downloading ResNeSt model

### ISSUE THREAD

**Issue by jakefleisig** [zhanghang1989/PyTorch-Encoding#395]
Hello, it seems as if I cannot download the ADE20k ResNeSt-101 pretrained backbone.  I have tried upgrading to the latest beta and that did not work either.  I am also specifying `pretrained=False` and it still attempts to pull it from the internet.  Please help.  Thank you!

```
Downloading /root/.encoding/models/resnest101-966fb78c.zip from https://s3.us-west-1.wasabisys.com/encoding/models/resnest101-966fb78c.zip...
Traceback (most recent call last):
  File "/app/src/roads/inference.py", line 159, in <module>
    main()
  File "/app/src/roads/inference.py", line 49, in main
    net = encoding.models.get_model('DeepLab_ResNeSt101_ADE', pretrained=False)
  File "/opt/conda/lib/python3.6/site-packages/encoding/models/model_zoo.py", line 76, in get_model
    net = models[name](**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/encoding/models/sseg/deeplab.py", line 195, in get_deeplab_resnest101_ade
    return get_deeplab('ade20k', 'resnest101', pretrained, aux=True, root=root, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/encoding/models/sseg/deeplab.py", line 133, in get_deeplab
    model = DeepLabV3(datasets[dataset.lower()].NUM_CLASS, backbone=backbone, root=root, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/encoding/models/sseg/deeplab.py", line 40, in __init__
    super(DeepLabV3, self).__init__(nclass, backbone, aux, se_loss, norm_layer=norm_layer, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/encoding/models/sseg/base.py", line 71, in __init__
    *args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/encoding/models/sseg/base.py", line 51, in get_backbone
    net = models[name](**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/encoding/models/backbone/resnest.py", line 36, in resnest101
    get_model_file('resnest101', root=root)), strict=True)
  File "/opt/conda/lib/python3.6/site-packages/encoding/models/model_store.py", line 105, in get_model_file
    overwrite=True)
  File "/opt/conda/lib/python3.6/site-packages/encoding/utils/files.py", line 61, in download
    raise RuntimeError("Failed downloading url %s"%url)
RuntimeError: Failed downloading url https://s3.us-west-1.wasabisys.com/encoding/models/resnest101-966fb78c.zip
```

**Comment by 18bce133** [comment]
same Issue , Please resolve

**Comment by zhanghang1989** [comment]
I just re-enabled the downloading for these models. Could you try again?

**Comment by jakefleisig** [comment]
looks like you fixed it.  thank you!
