### ISSUE TITLE
AttributeError: module 'encoding._ext.encoding_lib' has no attribute 'Encoding_Float_scaledl2_forward'

### ISSUE THREAD

**Issue by hfut-fan** [zhanghang1989/PyTorch-Encoding#49]
Hi Z-Hang:

When i test EncNet on CIFAR-10 using :
`python main.py --dataset cifar10 --model encnetdrop --widen 8 --ncodes 32 --resume model/encnet_cifar.pth.tar --eval`

 I got the following error.Could you help me solve it.

(`python setup.py install` has done and successed. )

my_env: pytorch0.4,anaconda3,ubuntu16.04

```
Using step LR Scheduler!
:   0%|                                                                          | 0/79 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 172, in <module>
    main()
  File "main.py", line 154, in main
    test(args.start_epoch)
  File "main.py", line 116, in test
    output = model(data)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 112, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/newP/En/PyTorch-Encoding/experiments/recognition/model/encnetdrop.py", line 59, in forward
    return self.model(input)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/newP/En/PyTorch-Encoding/experiments/recognition/model/mynn.py", line 157, in forward
    out = self.se(out)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/newP/En/PyTorch-Encoding/experiments/recognition/model/mynn.py", line 127, in forward
    y = self.fc(x).view(b, c, 1, 1)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/nn/encoding.py", line 151, in forward
    A = F.softmax(scaledL2(X, self.codewords, self.scale), dim=1)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 139, in scaledL2
    return _scaledL2.apply(X, C, S)
  File "/root/anaconda3/lib/python3.6/site-packages/encoding/functions/encoding.py", line 93, in forward
    encoding_lib.Encoding_Float_scaledl2_forward(SL, X, C, S)
AttributeError: module 'encoding._ext.encoding_lib' has no attribute 'Encoding_Float_scaledl2_forward'
````

**Comment by mario98** [comment]
Could be related to #44 
Check if `/root/anaconda3/lib/python3.6/site-packages/encoding/_ext` does contain an `__init__.py` and if not, copy if from the directory where you have compiled PyTorch-Encoding
from. There should be the missing `__init__.py` for the `_ext` folder somewhere.

**Comment by zhanghang1989** [comment]
Hi @mario98 , the `__init__.py` should be automatically generated.

**Comment by hfut-fan** [comment]
@mario98 ， Thank you !  It has worked.

In detail: 
-   I copy `__init__.py` file from` PyTorch-Encoding/encoding/_ext`  to  `/root/anaconda3/lib/python3.6/site-packages/encoding/_ext`  folder.
-  recompile `setup.py`. 
   -  `python setup.py clean`
   -  `python setup.py install`

-  run your demo again

**Comment by zhanghang1989** [comment]
Please checkout the newest version and see if you still have the trouble. See details in PR https://github.com/zhanghang1989/PyTorch-Encoding/pull/51
