### ISSUE TITLE
How to use the DataParallelCriterion ,DataParallelModel

### ISSUE THREAD

**Issue by lxtGH** [zhanghang1989/PyTorch-Encoding#54]
I fllow the insturction in this [page](http://hangzh.com/PyTorch-Encoding/parallel.html) in my code.
However I got this error.
Traceback (most recent call last):
  File "train_psp_resnet101.py", line 232, in <module>
    train(cfg)
  File "train_psp_resnet101.py", line 124, in train
    loss = loss_fn(outputs, labels)
  File "/home/xiangtai/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiangtai/anaconda3/lib/python3.6/site-packages/encoding/parallel.py", line 134, in forward
    outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/home/xiangtai/anaconda3/lib/python3.6/site-packages/encoding/parallel.py", line 188, in _criterion_parallel_apply
    raise output
  File "/home/xiangtai/anaconda3/lib/python3.6/site-packages/encoding/parallel.py", line 163, in _worker
    output = module(*(input + target), **kwargs)
TypeError: add() received an invalid combination of arguments - got (tuple), but expected one of:
 * (Tensor other, float alpha)
 * (float other, float alpha)

the outputs is a list,each item is a small tensor(each tensor is on different gpu), labels is not a list, but a tensor on gpu:0

**Comment by AssassinCroc** [comment]
This issue still persists, 
  File "train.py", line 495, in train
    main_los = criterion(main_loss, gts)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 468, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/encoding/parallel.py", line 134, in forward
    outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/opt/conda/lib/python3.6/site-packages/encoding/parallel.py", line 188, in _criterion_parallel_apply
    raise output
  File "/opt/conda/lib/python3.6/site-packages/encoding/parallel.py", line 163, in _worker
    output = module(*(input + target), **kwargs)
TypeError: add() received an invalid combination of arguments - got (tuple), but expected one of:
 * (Tensor other, Number alpha)
 * (Number other, Number alpha)

**Comment by lxtGH** [comment]
@AssassinCroc  make the output be tuple can solve this problem

**Comment by PkuRainBow** [comment]
@lxtGH How to make the output to be tuple? could you  show me the exact solution?

**Comment by lxtGH** [comment]
@PkuRainBow Yes，just` return x_dsn,  x` can also  work

**Comment by tonysy** [comment]
I meet the same error, and pytorch=0.4.1, while I try @lxtGH  solution, but it persists. 
And I found there are something wrong in parallel.py

I have fixed this error by the following:

In DataParallelCriterion.forward()

```python
replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
targets = tuple(targets_per_gpu[0] for targets_per_gpu in targets)
outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
```


In _criterion_parallel_apply()

```python
try:
        with torch.cuda.device(device):
                output = module(input, target)
        with lock:
                results[i] = output
except Exception as e:
```
It works for me, hope it helps!
