### ISSUE TITLE
ImportError: cannot import name 'BaseNet'

### ISSUE THREAD

**Issue by heyuCute** [zhanghang1989/PyTorch-Encoding#68]
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from models import get_segmentation_model
  File "/media/ubuntu/HDD/heyu/PyTorch-Encoding/encoding/models/__init__.py", line 6, in <module>
    from encnet import get_encnet
  File "/media/ubuntu/HDD/heyu/PyTorch-Encoding/encoding/models/encnet.py", line 15, in <module>
    from base import BaseNet
ImportError: cannot import name 'BaseNet'

the encnet.py can not import  BaseNet ,  but if we create a new python file, and  import the 'BaseNet',  there is no error.  Can you help me with this problem?  Thank you ~

**Comment by zhanghang1989** [comment]
Do you still have the problem? Now the code can be pip installed by running
```
pip install torch-encoding
```

**Comment by zhanghang1989** [comment]
Closing inactive issue. Feel free to reopen is still having the troubles.
