### ISSUE TITLE
PermissionError encoding/lib/cpu/lock

### ISSUE THREAD

**Issue by studentz** [zhanghang1989/PyTorch-Encoding#74]
- Installing system-wide  Pytorch-Encoding I got the next error.
- Commands

`sudo -H pip3 install --upgrade --no-cache-dir torch-encoding`
`python3`
`>>>  import torch `
 `>>> import encoding`
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.5/site-packages/encoding/__init__.py", line 13, in <module>
from . import nn, functions, dilated, parallel, utils, models, datasets
File "/usr/local/lib/python3.5/site-packages/encoding/nn/__init__.py", line 12, in <module>
from .encoding import *
File "/usr/local/lib/python3.5/site-packages/encoding/nn/encoding.py", line 18, in <module>
from ..functions import scaledL2, aggregate
File "/usr/local/lib/python3.5/site-packages/encoding/functions/__init__.py", line 2, in <module>
from .encoding import *
File "/usr/local/lib/python3.5/site-packages/encoding/functions/encoding.py", line 13, in <module>
from .. import lib
File "/usr/local/lib/python3.5/site-packages/encoding/lib/__init__.py", line 12, in <module>
], build_directory=cpu_path, verbose=False)
File "/usr/local/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 476, in load
if baton.try_acquire():
File "/usr/local/lib/python3.5/site-packages/torch/utils/file_baton.py", line 29, in try_acquire
self.fd = os.open(self.lock_file_path, os.O_CREAT | os.O_EXCL)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/site-packages/encoding/lib/cpu/lock'
```

If you need more information please let me know it.

Thanks

**Comment by zhanghang1989** [comment]
I see the problem. It is because you were using 'sudo pip install' and the files are post compiled after installation. 
1. A hacky way you can try is writing a file `hacky.py` with `import encoding`, and run
```
sudo python hacky.py
```

2. The best way to do it is to install with anaconda without sudo command

**Comment by zhanghang1989** [comment]
Closing inactive issue. Feel free to reopen is still having the troubles.

**Comment by monk42** [comment]
Thanks,your work! How to write the hacky.py? can you give me some suggestion?

**Comment by wlj567** [comment]
您好，我并不是安装库，而是运行test.py出现的错误，报错和上面一样，请问您知道这是什么原因吗？ @zhanghang1989

**Comment by zhanghang1989** [comment]
这个是因为用了 sudo install 引起的

**Comment by wlj567** [comment]
是直接用pip install 安装吗？

**Comment by zhanghang1989** [comment]
> 是直接用pip install 安装吗？

是的，不要用 sudo pip install。一个简单的解决方法就行先 sudo python test.py 跑一下

**Comment by wlj567** [comment]
好的，谢谢您的回复
