### ISSUE TITLE
When training with command "python -W ignore "train.py" --dataset pascal_aug --model encnet --aux --se-loss --eval --epochs 120 --backbone resnet101"

### ISSUE THREAD

**Issue by my462** [zhanghang1989/PyTorch-Encoding#93]
Using poly LR Scheduler!
Starting Epoch: 0
Total Epoches: 120
  0%|                                                                                                                                                                   | 0/1419 [00:00<?, ?it/s]
=>Epoches 0, learning rate = 0.0005,                 previous best = 0.0000
Train loss: 3.770:   0%|2                                                                                                                                     | 3/1419 [00:15<2:25:53,  6.18s/itTraceback (most recent call last):
  File "train.py", line 179, in <module>
    trainer.training(epoch)
  File "train.py", line 110, in training
    loss.backward()
  File "/root/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag

**Comment by my462** [comment]
Everything works fine with backbone resnet50

**Comment by my462** [comment]
Seems to be something with my GPU memory.
After I set the batch size to 4 from 8 it goes fine.
